// Copyright 2026 Jacob Delgado
// SPDX-License-Identifier: Apache-2.0

package hooks

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"go.yaml.in/yaml/v3"
)

// GitHook is a hook script found in the hooks directory.
type GitHook struct {
	Name   string
	Script string
}

// File is a file a generated configuration needs written.
type File struct {
	// Path is relative to the repository root.
	Path     string
	Contents string
}

// Generated is a lefthook configuration and the scripts it runs.
type Generated struct {
	Config  string
	Scripts []File
}

// configFileName is the configuration Write creates.
const configFileName = "lefthook.yml"

// Permissions for what Write creates: a configuration anyone may read, and
// scripts git's hooks can run.
const (
	configMode os.FileMode = 0o644
	scriptMode os.FileMode = 0o755
	dirMode    os.FileMode = 0o755
)

// minimumNumberWidth pads job numbers so that ten or more still sort in order.
const minimumNumberWidth = 2

// yamlIndent is the indentation lefthook's own examples use.
const yamlIndent = 2

// executableBits are the permission bits git checks before running a hook.
const executableBits = 0o111

// gitHookNames are the hooks git runs, in the order git documents them.
func gitHookNames() []string {
	return []string{
		"applypatch-msg", "pre-applypatch", "post-applypatch", "pre-commit", "pre-merge-commit",
		"prepare-commit-msg", "commit-msg", "post-commit", "pre-rebase", "post-checkout", "post-merge",
		"pre-push", "pre-receive", "update", "proc-receive", "post-receive", "post-update",
		"reference-transaction", "push-to-checkout", "pre-auto-gc", "post-rewrite", "sendemail-validate",
		"fsmonitor-watchman", "p4-changelist", "p4-prepare-changelist", "p4-post-changelist",
		"p4-pre-submit", "post-index-change",
	}
}

// ExistingHooks finds the hooks git would run from a hooks directory, in git's
// order: files named for a hook, runnable as one, that lefthook does not already
// manage. Whether a file is runnable is decided by goos, since Windows has no
// executable bit to check.
func ExistingHooks(hooksDir fs.FS, goos string) []GitHook {
	var found []GitHook

	for _, name := range gitHookNames() {
		info, err := fs.Stat(hooksDir, name)
		if err != nil || info.IsDir() || !runnableHook(info.Mode(), goos) {
			continue
		}

		script, err := fs.ReadFile(hooksDir, name)
		if err != nil || strings.Contains(string(script), "lefthook") {
			continue
		}

		found = append(found, GitHook{Name: name, Script: string(script)})
	}

	return found
}

// runnableHook reports whether git would run a file as a hook: executable on
// Unix, and any regular file on Windows, where Go reports no executable bit
// (0666 or 0444 for every file) so the bit cannot be the test.
func runnableHook(mode fs.FileMode, goos string) bool {
	if goos == "windows" {
		return true
	}

	return mode.Perm()&executableBits != 0
}

// Structured writes a configuration that runs each hook of plain commands as
// lefthook jobs, and keeps any other hook as a script. Only a hook whose every
// line is a command lefthook can run on its own is converted: one that reads
// its arguments, branches, or sets variables is kept whole rather than guessed
// at.
func Structured(hooks []GitHook) Generated {
	return generate(hooks, generation{
		convertsPlainHooks: true,
		howHooksRun:        "Hooks it could run as jobs are jobs; the rest run from .lefthook as scripts.",
	})
}

// Verbatim writes a configuration that keeps every hook as the script it is.
func Verbatim(hooks []GitHook) Generated {
	return generate(hooks, generation{
		howHooksRun: "Every hook runs from .lefthook as the script it was.",
	})
}

// generatedFrom opens the header of every configuration, whichever mode wrote it.
const generatedFrom = "Generated by workflow from the hooks this repository already had."

// generation is what sets one mode's configuration apart: whether a hook of
// plain commands becomes jobs, and the header line saying which it did.
type generation struct {
	convertsPlainHooks bool
	howHooksRun        string
}

// generate builds the configuration the way mode says to.
func generate(hooks []GitHook, mode generation) Generated {
	document := mapping()
	document.HeadComment = generatedFrom + "\n" + mode.howHooksRun

	var scripts []File

	for _, hook := range hooks {
		commands, plain := plainCommands(hook.Script)

		if mode.convertsPlainHooks && plain {
			appendPair(document, hook.Name, commandsHook(commands))

			continue
		}

		appendPair(document, hook.Name, scriptHook(hook))
		scripts = append(scripts, File{
			Path: path.Join(".lefthook", hook.Name, hook.Name), Contents: hook.Script,
		})
	}

	return Generated{Config: render(document), Scripts: scripts}
}

// commandsHook is a hook of numbered jobs. It is piped, so the first failure
// stops the rest, as set -e did; and numbered, because lefthook runs piped jobs
// in the order of their NAMES rather than as written — checked against lefthook
// 2.1, where "zeta" ran after "alpha".
func commandsHook(commands []string) *yaml.Node {
	jobs := mapping()
	width := len(strconv.Itoa(len(commands)))

	for index, command := range commands {
		job := mapping()
		appendPair(job, "run", scalar(command))
		appendPair(jobs, fmt.Sprintf("%0*d-%s", max(minimumNumberWidth, width), index+1, jobName(command)), job)
	}

	hook := mapping()
	appendPair(hook, "piped", &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: "true"})
	appendPair(hook, "commands", jobs)

	return hook
}

// scriptHook is a hook that runs its script from .lefthook, which lefthook hands
// git's arguments.
func scriptHook(hook GitHook) *yaml.Node {
	script := mapping()
	appendPair(script, "runner", scalar(runner(hook.Script)))

	scripts := mapping()
	appendPair(scripts, hook.Name, script)

	node := mapping()
	appendPair(node, "scripts", scripts)

	return node
}

// runner is what runs a script, read from its shebang: the interpreter's name
// and its arguments, looking through env. With no shebang, git runs it with sh.
func runner(script string) string {
	first, _, _ := strings.Cut(script, "\n")
	if !strings.HasPrefix(first, "#!") {
		return "sh"
	}

	words := strings.Fields(strings.TrimPrefix(first, "#!"))
	if len(words) == 0 {
		return "sh"
	}

	interpreter, args := path.Base(words[0]), words[1:]
	if interpreter == "env" {
		args = withoutEnvOptions(args)
		if len(args) == 0 {
			return "sh"
		}

		interpreter, args = path.Base(args[0]), args[1:]
	}

	return strings.Join(append([]string{interpreter}, args...), " ")
}

// withoutEnvOptions drops the options env eats before the program it runs: its
// flags (with -u's variable name), and VAR=value assignments. What is left
// begins with the interpreter, or is empty when the line named none.
func withoutEnvOptions(args []string) []string {
	for len(args) > 0 {
		switch {
		case args[0] == "-u" && len(args) > 1:
			args = args[2:]
		case strings.HasPrefix(args[0], "-"):
			args = args[1:]
		case strings.Contains(args[0], "="):
			args = args[1:]
		default:
			return args
		}
	}

	return args
}

// convertibleRunner is the one interpreter whose scripts convert to jobs.
// lefthook runs a job with `sh -c`, so a script that already runs under sh keeps
// its meaning as jobs; a bash or zsh script might not, and stays a script.
const convertibleRunner = "sh"

// plainCommands reads a script's commands, reporting whether it converts to a
// piped job list without changing what it does. It converts only a script that
// turns errexit on itself, since the piped list stops at the first failure — a
// script that did not would run on past a failing command, and converting it
// would silently start stopping.
func plainCommands(script string) ([]string, bool) {
	if strings.Fields(runner(script))[0] != convertibleRunner {
		return nil, false
	}

	var commands []string

	errexit := false

	for raw := range strings.SplitSeq(script, "\n") {
		line := strings.TrimSpace(raw)

		switch {
		case line == "" || strings.HasPrefix(line, "#"):
			continue
		case setOption().MatchString(line):
			errexit = errexit || errexitOption().MatchString(line)
		case !plainCommand(line):
			return nil, false
		default:
			commands = append(commands, line)
		}
	}

	return commands, errexit && len(commands) > 0
}

// setOption matches any `set -flags` line; a piped job list runs the commands
// but honors none of the options, so only the errexit ones below are safe.
func setOption() *regexp.Regexp {
	return regexp.MustCompile(`^set\s+-[a-zA-Z]+(\s+\S+)?$`)
}

// errexitOption matches a `set` line that turns errexit on and nothing a piped
// job list cannot also do: short flags including -e (with -u or -x alongside is
// fine), or the long -o errexit. `set -o pipefail` is deliberately not here — a
// piped job list cannot reproduce it, so a script that needs it stays whole.
func errexitOption() *regexp.Regexp {
	return regexp.MustCompile(`^set\s+(-[a-z]*e[a-z]*|-o\s+errexit)$`)
}

// plainCommand reports a line that means the same run on its own as it did in
// its script: no variable or command substitution, no heredoc or process
// substitution, no pipe or background or continuation, no assignment, and not a
// keyword or builtin that only means something in sequence. Any `$` at all is
// out — a piped job list cannot carry the argument or variable it reads — and so
// is any `|` or `&`, since lefthook cannot reproduce a pipeline's pipefail or a
// job that runs in the background.
func plainCommand(line string) bool {
	for _, marker := range []string{"$", "`", "<<", "<(", ">(", "|", "&"} {
		if strings.Contains(line, marker) {
			return false
		}
	}

	first := strings.Fields(line)[0]

	return !strings.HasSuffix(line, "\\") && !strings.Contains(first, "=") && !strings.HasSuffix(first, "()") &&
		!slices.Contains(shellWords(), first)
}

// shellWords begin a line that is not a command by itself.
func shellWords() []string {
	return []string{
		"if", "then", "else", "elif", "fi", "for", "while", "until", "do", "done", "case", "esac",
		"function", "{", "}", "[", "[[", "(", ")", "exec", "exit", "return", "source", ".", "cd", "export",
		"trap", "shift", "read", "local", "declare", "readonly", "unset", "set",
		"pushd", "popd", "umask", "alias", "eval", "wait",
	}
}

// toolsWithVerbs name a job by their subcommand too: "go vet", not "go".
func toolsWithVerbs() []string {
	return []string{"go", "npm", "npx", "yarn", "pnpm", "make", "task", "cargo", "bundle", "mise", "uv", "poetry"}
}

// jobName names a job for its command.
func jobName(command string) string {
	words := strings.Fields(command)
	name := path.Base(words[0])

	if slices.Contains(toolsWithVerbs(), name) && len(words) > 1 && !strings.HasPrefix(words[1], "-") {
		name += "-" + words[1]
	}

	cleaned := strings.Trim(nonName().ReplaceAllString(strings.ToLower(name), "-"), "-")
	if cleaned == "" {
		return "job"
	}

	return cleaned
}

// nonName matches what cannot be in a job name.
func nonName() *regexp.Regexp {
	return regexp.MustCompile(`[^a-z0-9]+`)
}

// mapping is an empty YAML mapping.
func mapping() *yaml.Node {
	return &yaml.Node{Kind: yaml.MappingNode}
}

// scalar is a YAML string. The tag is what makes the encoder quote a value that
// would otherwise read as another type: without it, a hook line of just "false"
// was written as run: false, which lefthook read as a bool and ran as "0".
func scalar(value string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: value}
}

// appendPair adds a key and its value to a mapping.
func appendPair(node *yaml.Node, key string, value *yaml.Node) {
	node.Content = append(node.Content, scalar(key), value)
}

// render writes a document with two-space indentation, which is what
// lefthook's own examples use.
func render(document *yaml.Node) string {
	var out bytes.Buffer

	encoder := yaml.NewEncoder(&out)
	encoder.SetIndent(yamlIndent)

	// A mapping of strings cannot fail to encode.
	_ = encoder.Encode(document)
	_ = encoder.Close()

	return out.String()
}

// Write creates the configuration and its scripts in a repository. It never
// replaces anything: not a lefthook configuration under any name lefthook
// reads, and not an existing script.
func Write(dir string, generated Generated) error {
	if HasConfig(os.DirFS(dir)) {
		return fmt.Errorf("%w: this repository already has a lefthook configuration", fs.ErrExist)
	}

	// Track what this call creates and undo it on any failure, so a write that
	// stops part-way leaves no lefthook.yml naming scripts it never wrote — which
	// would otherwise block the offer from ever being tried again.
	var written []string

	remove := func() {
		for _, w := range slices.Backward(written) {
			_ = os.Remove(w)
		}
	}

	err := create(filepath.Join(dir, configFileName), generated.Config, configMode)
	if err != nil {
		return err
	}

	written = append(written, filepath.Join(dir, configFileName))

	for _, script := range generated.Scripts {
		target := filepath.Join(dir, filepath.FromSlash(script.Path))

		err = os.MkdirAll(filepath.Dir(target), dirMode)
		if err != nil {
			remove()

			return fmt.Errorf("creating %s: %w", filepath.Dir(script.Path), err)
		}

		err = create(target, script.Contents, scriptMode)
		if err != nil {
			remove()

			return err
		}

		written = append(written, target)
	}

	return nil
}

// create writes a new file, refusing one that already exists.
func create(target, contents string, mode os.FileMode) error {
	//nolint:gosec // the path is the repository root joined with a name built here
	file, err := os.OpenFile(target, os.O_WRONLY|os.O_CREATE|os.O_EXCL, mode)
	if err != nil {
		return fmt.Errorf("creating %s: %w", target, err)
	}

	_, writeErr := file.WriteString(contents)

	err = errors.Join(writeErr, file.Close())
	if err != nil {
		return fmt.Errorf("writing %s: %w", target, err)
	}

	return nil
}
