import type { KeyList } from '@/api/generated/types.gen.ts'

// The key list a server serves with no ui.keys, as tui.KeyActions lists it,
// and single-key shortcuts on — trimmed to the actions this page binds, the
// only ones it reads — so the mockup's ? sheet, palette and keys work with no
// backend.
export const mockKeys: KeyList = {
  single_key_shortcuts: true,
  actions: [
    {
      action: 'jump-to-pane',
      help: 'jump to pane',
      group: 'Moving around',
      shown: '1-9',
      keys: ['1', '2', '3', '4', '5', '6', '7', '8', '9'],
    },
    { action: 'change-status', help: 'change status', group: 'Issues', shown: 't', keys: ['t'] },
    { action: 'comment', help: 'comment', group: 'Issues', shown: 'c', keys: ['c'] },
    { action: 'assign', help: 'assign', group: 'Issues', shown: 'a', keys: ['a'] },
    { action: 'log-work', help: 'log work', group: 'Issues', shown: 'w', keys: ['w'] },
    { action: 'search-issues', help: 'search', group: 'Issues', shown: '/', keys: ['/'] },
    { action: 'switch-view', help: 'switch view', group: 'Issues', shown: 'v', keys: ['v'] },
    { action: 'load-more', help: 'load more', group: 'Issues', shown: 'ctrl+n', keys: ['ctrl+n'] },
    { action: 'open-link', help: 'open', group: 'Issues', shown: 'o', keys: ['o'] },
    {
      action: 'track-issue',
      help: 'track in Taskwarrior',
      group: 'Issues',
      shown: 'T',
      keys: ['T'],
    },
    {
      action: 'link-issue',
      help: 'link issue',
      group: 'Branch and Commits',
      shown: 'i',
      keys: ['i'],
    },
    {
      action: 'rebase',
      help: 'rebase onto base',
      group: 'Branch and Commits',
      shown: 'u',
      keys: ['u'],
    },
    { action: 'push', help: 'push', group: 'Branch and Commits', shown: 'P', keys: ['P'] },
    {
      action: 'stage-all',
      help: 'stage all',
      group: 'Branch and Commits',
      shown: 'a',
      keys: ['a'],
    },
    {
      action: 'unstage-all',
      help: 'unstage all',
      group: 'Branch and Commits',
      shown: 'U',
      keys: ['U'],
    },
    { action: 'commit', help: 'commit', group: 'Branch and Commits', shown: 'c', keys: ['c'] },
    { action: 'amend', help: 'amend', group: 'Branch and Commits', shown: 'A', keys: ['A'] },
    { action: 'fixup', help: 'fix up', group: 'Branch and Commits', shown: 'f', keys: ['f'] },
    {
      action: 'run-pre-commit',
      help: 'run pre-commit',
      group: 'Branch and Commits',
      shown: 'h',
      keys: ['h'],
    },
    {
      action: 'set-up-lefthook',
      help: 'set up lefthook',
      group: 'Branch and Commits',
      shown: 'g',
      keys: ['g'],
    },
    {
      action: 'open-pull-request',
      help: 'open pull request',
      group: 'Review and Slack',
      shown: 'n',
      keys: ['n'],
    },
    {
      action: 'rerun-checks',
      help: 're-run checks',
      group: 'Review and Slack',
      shown: 'R',
      keys: ['R'],
    },
    { action: 'merge', help: 'merge', group: 'Review and Slack', shown: 'M', keys: ['M'] },
    {
      action: 'finish-branch',
      help: 'finish branch',
      group: 'Review and Slack',
      shown: 'F',
      keys: ['F'],
    },
    {
      action: 'post',
      help: 'announce to Slack',
      group: 'Review and Slack',
      shown: 'p',
      keys: ['p'],
    },
    { action: 'sort-reviews', help: 'sort', group: 'Reviews', shown: 'O', keys: ['O'] },
    { action: 'start-stop', help: 'start/stop', group: 'Tasks', shown: 's', keys: ['s'] },
    { action: 'mark-done', help: 'mark done', group: 'Tasks', shown: 'd', keys: ['d'] },
    { action: 'add-task', help: 'add', group: 'Tasks', shown: 'a', keys: ['a'] },
    { action: 'annotate-task', help: 'annotate', group: 'Tasks', shown: 'A', keys: ['A'] },
    { action: 'modify-task', help: 'modify', group: 'Tasks', shown: 'e', keys: ['e'] },
    { action: 'undo-task', help: 'undo', group: 'Tasks', shown: 'u', keys: ['u'] },
    { action: 'sync-tasks', help: 'sync', group: 'Tasks', shown: 'S', keys: ['S'] },
    { action: 'search-tasks', help: 'search', group: 'Tasks', shown: '/', keys: ['/'] },
    { action: 'sort-tasks', help: 'sort', group: 'Tasks', shown: 'O', keys: ['O'] },
    { action: 'earlier', help: 'earlier', group: 'Summary', shown: '[', keys: ['['] },
    { action: 'later', help: 'later', group: 'Summary', shown: ']', keys: [']'] },
    { action: 'today', help: 'today', group: 'Summary', shown: 't', keys: ['t'] },
    { action: 'copy-summary', help: 'copy as Markdown', group: 'Summary', shown: 'Y', keys: ['Y'] },
    {
      action: 'favorite-directory',
      help: 'favorite',
      group: 'Repositories',
      shown: 'f',
      keys: ['f'],
    },
    { action: 'go-to-directory', help: 'go to', group: 'Repositories', shown: 'g', keys: ['g'] },
    { action: 'toggle-help', help: 'keys', group: 'Everywhere', shown: '?', keys: ['?'] },
  ],
}
