// Copyright 2026 Jacob Delgado
// SPDX-License-Identifier: Apache-2.0

package docsgen_test

import (
	"bytes"
	"errors"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/jacob-delgado/workflow/internal/docsgen"
)

// handWritten is a page no run of docsgen wrote.
const handWritten = "# Notes\n\nKept by hand.\n"

// generate runs docsgen into dir, failing the test when it does not succeed.
func generate(t *testing.T, dir string) {
	t.Helper()

	var stderr bytes.Buffer

	if code := docsgen.Run([]string{dir}, io.Discard, &stderr); code != 0 {
		t.Fatalf("docsgen %s exited %d: %s", dir, code, stderr.String())
	}
}

// writePage writes contents to the page name in dir.
func writePage(t *testing.T, dir, name, contents string) string {
	t.Helper()

	path := filepath.Join(dir, name)

	err := os.WriteFile(path, []byte(contents), 0o600)
	if err != nil {
		t.Fatalf("writing %s: %v", path, err)
	}

	return path
}

// readPage is what the page name in dir holds.
func readPage(t *testing.T, dir, name string) string {
	t.Helper()

	contents, err := os.ReadFile(filepath.Join(dir, name))
	if err != nil {
		t.Fatalf("reading %s: %v", name, err)
	}

	return string(contents)
}

func TestRunWritesAPageForEveryCommand(t *testing.T) {
	t.Parallel()

	// Arrange
	dir := filepath.Join(t.TempDir(), "reference")

	// Act
	generate(t, dir)

	// Assert
	pages := []string{"workflow.md", "workflow_config.md", "workflow_config_init.md", "workflow_completion.md"}
	for _, name := range pages {
		_, err := os.Stat(filepath.Join(dir, name))
		if err != nil {
			t.Errorf("docsgen wrote no %s: %v", name, err)
		}
	}
}

func TestRunKeepsAHandWrittenPageAndRemovesAStaleGeneratedOne(t *testing.T) {
	t.Parallel()

	// Arrange
	dir := t.TempDir()
	generate(t, dir)

	// A page an earlier run wrote for a command that is gone since.
	stale := writePage(t, dir, "workflow_gone.md", readPage(t, dir, "workflow_config.md"))
	notes := writePage(t, dir, "notes.md", handWritten)

	// Act
	generate(t, dir)

	// Assert
	_, staleErr := os.Stat(stale)
	if !errors.Is(staleErr, fs.ErrNotExist) {
		t.Errorf("the stale generated page is still there (%v), want it removed", staleErr)
	}

	kept, err := os.ReadFile(notes)
	if err != nil || string(kept) != handWritten {
		t.Errorf("the hand-written page holds %q (%v), want it left as it was", kept, err)
	}
}

func TestRunTitlesEachPageByItsCommandAndSortsItByDepth(t *testing.T) {
	t.Parallel()

	// Arrange
	dir := t.TempDir()

	// Act
	generate(t, dir)

	// Assert
	page := readPage(t, dir, "workflow_config_init.md")
	if !strings.HasPrefix(page, "---\ntitle: \"workflow config init\"\nweight: 30\n---\n") ||
		!strings.Contains(page, "Generated by `task docs:gen`") {
		t.Errorf("workflow_config_init.md opens:\n%.200s\nwant its command as the title, weight 30, and the notice", page)
	}
}

func TestRunLinksEachPageAsHugoServesIt(t *testing.T) {
	t.Parallel()

	// Arrange
	dir := t.TempDir()

	// Act
	generate(t, dir)

	// Assert
	if page := readPage(t, dir, "workflow_config.md"); !strings.Contains(page, "(../workflow_config_init/)") {
		t.Errorf("workflow_config.md does not link init as Hugo serves it:\n%s", page)
	}
}

func TestRunRefusesACallThatNamesNoDirectory(t *testing.T) {
	t.Parallel()

	// Arrange
	var stderr bytes.Buffer

	// Act
	code := docsgen.Run(nil, io.Discard, &stderr)

	// Assert
	if code != 1 || !strings.Contains(stderr.String(), "usage: docsgen <output-directory>") {
		t.Errorf("docsgen with no directory exited %d saying %q, want 1 and its usage", code, stderr.String())
	}
}

// sealed makes dir readable but not writable for the test's end.
func sealed(t *testing.T, dir string) {
	t.Helper()

	restricted(t, dir, 0o500)
}

// restricted gives dir mode for the test's end, skipping as root, which reads
// and writes whatever a mode says, and on Windows, whose directories keep no
// such bits.
func restricted(t *testing.T, dir string, mode os.FileMode) {
	t.Helper()

	if os.Geteuid() == 0 || runtime.GOOS == "windows" {
		t.Skip("a directory's mode does not keep this user from reading or writing it here")
	}

	err := os.Chmod(dir, mode)
	if err != nil {
		t.Fatal(err)
	}

	t.Cleanup(func() { _ = os.Chmod(dir, 0o700) })
}

func TestRunSaysWhyItCouldNotWriteTheReference(t *testing.T) {
	t.Parallel()

	cases := map[string]struct {
		// where makes the directory a run is pointed at, and the way it fails.
		where func(t *testing.T) string
		want  string
	}{
		"a directory under a file": {want: "creating", where: func(t *testing.T) string {
			t.Helper()

			return filepath.Join(writePage(t, t.TempDir(), "file.md", handWritten), "reference")
		}},
		"a page it cannot read": {want: "reading", where: func(t *testing.T) string {
			t.Helper()

			dir := t.TempDir()
			page := writePage(t, dir, "notes.md", handWritten)
			sealed(t, dir)

			err := os.Chmod(page, 0o000)
			if err != nil {
				t.Fatal(err)
			}

			return dir
		}},
		"a stale page it cannot remove": {want: "removing stale page", where: func(t *testing.T) string {
			t.Helper()

			dir := t.TempDir()
			generate(t, dir)
			sealed(t, dir)

			return dir
		}},
		"a directory it cannot write the pages into": {want: "generating", where: func(t *testing.T) string {
			t.Helper()

			dir := t.TempDir()
			sealed(t, dir)

			return dir
		}},
	}

	for name, tt := range cases {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			// Arrange
			dir := tt.where(t)

			var stderr bytes.Buffer

			// Act
			code := docsgen.Run([]string{dir}, io.Discard, &stderr)

			// Assert
			if code != 1 || !strings.Contains(stderr.String(), tt.want) {
				t.Errorf("docsgen into %s exited %d saying %q, want 1 and %q", name, code, stderr.String(), tt.want)
			}
		})
	}
}

func TestRunNamesADirectoryItCannotList(t *testing.T) {
	t.Parallel()

	// Arrange
	// Writable and searchable but not readable: it can be made and written
	// into, but not listed for the pages an earlier run left.
	dir := t.TempDir()
	restricted(t, dir, 0o300)

	var stderr bytes.Buffer

	// Act
	code := docsgen.Run([]string{dir}, io.Discard, &stderr)

	// Assert
	if code != 1 || !strings.Contains(stderr.String(), "reading "+dir+": ") {
		t.Errorf("docsgen into an unlistable directory exited %d saying %q, want 1 and the directory named",
			code, stderr.String())
	}
}
