// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for CIState.
const (
	Failed  CIState = "failed"
	None    CIState = "none"
	Passed  CIState = "passed"
	Running CIState = "running"
)

// Valid indicates whether the value is a known member of the CIState enum.
func (e CIState) Valid() bool {
	switch e {
	case Failed:
		return true
	case None:
		return true
	case Passed:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for ChangeKind.
const (
	ChangeKindConflicted ChangeKind = "conflicted"
	ChangeKindCopied     ChangeKind = "copied"
	ChangeKindDeleted    ChangeKind = "deleted"
	ChangeKindModified   ChangeKind = "modified"
	ChangeKindNew        ChangeKind = "new"
	ChangeKindRenamed    ChangeKind = "renamed"
	ChangeKindUntracked  ChangeKind = "untracked"
)

// Valid indicates whether the value is a known member of the ChangeKind enum.
func (e ChangeKind) Valid() bool {
	switch e {
	case ChangeKindConflicted:
		return true
	case ChangeKindCopied:
		return true
	case ChangeKindDeleted:
		return true
	case ChangeKindModified:
		return true
	case ChangeKindNew:
		return true
	case ChangeKindRenamed:
		return true
	case ChangeKindUntracked:
		return true
	default:
		return false
	}
}

// Defines values for FollowUpAction.
const (
	Link       FollowUpAction = "link"
	Transition FollowUpAction = "transition"
)

// Valid indicates whether the value is a known member of the FollowUpAction enum.
func (e FollowUpAction) Valid() bool {
	switch e {
	case Link:
		return true
	case Transition:
		return true
	default:
		return false
	}
}

// Defines values for ForgeConfigKind.
const (
	ForgeConfigKindEmpty  ForgeConfigKind = ""
	ForgeConfigKindGithub ForgeConfigKind = "github"
	ForgeConfigKindGitlab ForgeConfigKind = "gitlab"
)

// Valid indicates whether the value is a known member of the ForgeConfigKind enum.
func (e ForgeConfigKind) Valid() bool {
	switch e {
	case ForgeConfigKindEmpty:
		return true
	case ForgeConfigKindGithub:
		return true
	case ForgeConfigKindGitlab:
		return true
	default:
		return false
	}
}

// Defines values for MessagingConfigKind.
const (
	MessagingConfigKindDiscord MessagingConfigKind = "discord"
	MessagingConfigKindEmpty   MessagingConfigKind = ""
	MessagingConfigKindSlack   MessagingConfigKind = "slack"
	MessagingConfigKindTeams   MessagingConfigKind = "teams"
	MessagingConfigKindWebhook MessagingConfigKind = "webhook"
)

// Valid indicates whether the value is a known member of the MessagingConfigKind enum.
func (e MessagingConfigKind) Valid() bool {
	switch e {
	case MessagingConfigKindDiscord:
		return true
	case MessagingConfigKindEmpty:
		return true
	case MessagingConfigKindSlack:
		return true
	case MessagingConfigKindTeams:
		return true
	case MessagingConfigKindWebhook:
		return true
	default:
		return false
	}
}

// Defines values for ProblemCode.
const (
	BadRequest    ProblemCode = "bad_request"
	Conflict      ProblemCode = "conflict"
	Internal      ProblemCode = "internal"
	NotFound      ProblemCode = "not_found"
	Unprocessable ProblemCode = "unprocessable"
	Unreachable   ProblemCode = "unreachable"
)

// Valid indicates whether the value is a known member of the ProblemCode enum.
func (e ProblemCode) Valid() bool {
	switch e {
	case BadRequest:
		return true
	case Conflict:
		return true
	case Internal:
		return true
	case NotFound:
		return true
	case Unprocessable:
		return true
	case Unreachable:
		return true
	default:
		return false
	}
}

// Defines values for PullRequestMergeable.
const (
	Clean     PullRequestMergeable = "clean"
	Conflicts PullRequestMergeable = "conflicts"
	Unknown   PullRequestMergeable = "unknown"
)

// Valid indicates whether the value is a known member of the PullRequestMergeable enum.
func (e PullRequestMergeable) Valid() bool {
	switch e {
	case Clean:
		return true
	case Conflicts:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for StatusCategory.
const (
	StatusCategoryDone          StatusCategory = "done"
	StatusCategoryIndeterminate StatusCategory = "indeterminate"
	StatusCategoryNew           StatusCategory = "new"
)

// Valid indicates whether the value is a known member of the StatusCategory enum.
func (e StatusCategory) Valid() bool {
	switch e {
	case StatusCategoryDone:
		return true
	case StatusCategoryIndeterminate:
		return true
	case StatusCategoryNew:
		return true
	default:
		return false
	}
}

// AnnounceRequest Where to post the announcement.
type AnnounceRequest struct {
	// Channel The channel to post to; empty uses the configured channel or the webhook.
	Channel string `json:"channel"`
}

// Announcement A composed announcement and where it would post.
type Announcement struct {
	// Channel The channel it posts to, or empty for a webhook's own channel.
	Channel string `json:"channel"`

	// Text The message that would be posted.
	Text string `json:"text"`
}

// Branch defines model for Branch.
type Branch struct {
	Ahead int `json:"ahead"`

	// Base The base branch, such as origin/main.
	Base   string `json:"base"`
	Behind int    `json:"behind"`

	// Commits The commits on this branch since its base.
	Commits []Commit `json:"commits"`

	// Detached Whether HEAD is detached rather than on a branch.
	Detached bool `json:"detached"`

	// Head The commit SHA; empty before the first commit.
	Head string `json:"head"`
	Name string `json:"name"`

	// Upstream The tracking branch; empty if never pushed.
	Upstream string `json:"upstream"`
}

// BranchConfig defines model for BranchConfig.
type BranchConfig struct {
	DefaultPrefix *string            `json:"default_prefix,omitempty"`
	Prefixes      *map[string]string `json:"prefixes,omitempty"`

	// SlugLimit The summary slug's length cap in a branch name; zero keeps 48.
	SlugLimit *int `json:"slug_limit,omitempty"`

	// Template The branch-name template; must contain {key}.
	Template *string `json:"template,omitempty"`
}

// CI defines model for CI.
type CI struct {
	Checks []Check `json:"checks"`
	Done   int     `json:"done"`
	Failed int     `json:"failed"`
	State  CIState `json:"state"`

	// Total Total checks; 0 on a forge that reports the pipeline whole.
	Total int `json:"total"`
}

// CIState defines model for CIState.
type CIState string

// Change defines model for Change.
type Change struct {
	Conflicted bool `json:"conflicted"`

	// HasUnstaged Whether there are unstaged edits to the same path.
	HasUnstaged bool `json:"has_unstaged"`

	// Kind What kind of change this is.
	Kind ChangeKind `json:"kind"`

	// OriginalPath The former path for a rename or copy; empty otherwise.
	OriginalPath *string `json:"original_path,omitempty"`
	Path         string  `json:"path"`

	// Staged Whether the change (or part of it) is staged.
	Staged bool `json:"staged"`
}

// ChangeKind What kind of change this is.
type ChangeKind string

// ChangeList defines model for ChangeList.
type ChangeList struct {
	Changes []Change `json:"changes"`
}

// Check defines model for Check.
type Check struct {
	Name  string  `json:"name"`
	State CIState `json:"state"`
	URL   string  `json:"url"`
}

// CheckoutRequest The branch to check out.
type CheckoutRequest struct {
	// Branch The local branch to switch the working tree to.
	//
	// Example: fix/PROJ-412-redact-tokens
	Branch string `json:"branch"`
}

// Comment defines model for Comment.
type Comment struct {
	Author string `json:"author"`
	Body   string `json:"body"`

	// Created RFC 3339; the zero time if the tracker's date was unreadable.
	Created time.Time `json:"created"`
}

// Commit defines model for Commit.
type Commit struct {
	Hash    string `json:"hash"`
	Subject string `json:"subject"`
}

// CommitConfig defines model for CommitConfig.
type CommitConfig struct {
	DefaultScope *string `json:"default_scope,omitempty"`

	// RefsTrailer The issue trailer's label, such as "Closes"; empty keeps "Refs".
	RefsTrailer *string `json:"refs_trailer,omitempty"`

	// SubjectLimit The longest a subject may be, in characters; zero keeps 72.
	SubjectLimit *int `json:"subject_limit,omitempty"`

	// Types The commit types the composer offers and validates against, in order; empty keeps the built-in Conventional Commit types.
	Types *[]string `json:"types,omitempty"`
}

// CommitRequest The parts of a Conventional Commit message for the staged changes.
type CommitRequest struct {
	// Body The optional message body, after a blank line.
	Body *string `json:"body,omitempty"`

	// Breaking Whether this is a breaking change, marked with "!".
	Breaking *bool `json:"breaking,omitempty"`

	// Scope The optional scope, written in parentheses after the type.
	Scope *string `json:"scope,omitempty"`

	// Subject The description written after the colon.
	//
	// Example: redact tokens before they reach the request log
	Subject string `json:"subject"`

	// Type The Conventional Commit type, such as feat or fix.
	//
	// Example: fix
	Type string `json:"type"`
}

// Config The whole configuration file. On a read, the four secret fields and the Jira header values are masked; on a write, a masked or empty secret keeps the stored value.
type Config struct {
	Branch      BranchConfig      `json:"branch"`
	Commit      CommitConfig      `json:"commit"`
	Forge       ForgeConfig       `json:"forge"`
	Jira        JiraConfig        `json:"jira"`
	Messaging   MessagingConfig   `json:"messaging"`
	PullRequest PullRequestConfig `json:"pull_request"`
	Store       StoreConfig       `json:"store"`
	Timing      TimingConfig      `json:"timing"`
	UI          UIConfig          `json:"ui"`
	Version     string            `json:"version"`
}

// CreateBranchRequest The issue to start work on by creating its branch.
type CreateBranchRequest struct {
	// IssueKey The issue to name and create a branch for.
	//
	// Example: PROJ-412
	IssueKey string `json:"issue_key"`
}

// FollowUp One offer after opening: to link the pull request on the branch's issue (POST /api/issues/{key}/link), or to move that issue to the review status (POST /api/issues/{key}/transition). A move is offered only when Jira offers one that needs no fields.
type FollowUp struct {
	Action FollowUpAction `json:"action"`

	// IssueKey The Jira issue the checked-out branch names.
	//
	// Example: PROJ-412
	IssueKey string `json:"issue_key"`

	// Status Set only on a transition — the status the issue would move to.
	//
	// Example: In Review
	Status *string `json:"status,omitempty"`
}

// FollowUpAction defines model for FollowUp.Action.
type FollowUpAction string

// ForgeConfig defines model for ForgeConfig.
type ForgeConfig struct {
	Cli  *bool   `json:"cli,omitempty"`
	Host *string `json:"host,omitempty"`

	// Kind Empty for auto-detect, else github or gitlab.
	Kind *ForgeConfigKind `json:"kind,omitempty"`

	// Token Masked on read; empty or masked on write keeps the stored value.
	Token *string `json:"token,omitempty"`
}

// ForgeConfigKind Empty for auto-detect, else github or gitlab.
type ForgeConfigKind string

// Health defines model for Health.
type Health struct {
	// DryRun Whether writes are held back (the --dry-run flag).
	DryRun bool `json:"dry_run"`

	// ForgeNoun What the repository's forge calls a proposed change, lowercase — a "merge request" on GitLab and a "pull request" everywhere else — so the browser says what the terminal and the command line say.
	//
	// Example: merge request
	ForgeNoun string `json:"forge_noun"`

	// ForgeSigil The mark the forge writes before a proposed change's number: "!" on GitLab, "#" everywhere else.
	//
	// Example: !
	ForgeSigil string `json:"forge_sigil"`

	// Version The binary's version, or a short commit for a dev build.
	Version string `json:"version"`
}

// Issue defines model for Issue.
type Issue struct {
	// Key Example: PROJ-412
	Key string `json:"key"`

	// Priority May be empty.
	Priority *string `json:"priority,omitempty"`

	// Status The human status name, such as "In Progress".
	Status         string         `json:"status"`
	StatusCategory StatusCategory `json:"status_category"`
	Summary        string         `json:"summary"`

	// Type The issue type name, such as Bug or Story.
	Type string `json:"type"`
}

// IssueDetail defines model for IssueDetail.
type IssueDetail struct {
	// Assignee Who the issue is assigned to; absent when no one is.
	Assignee *string `json:"assignee,omitempty"`

	// CommentTotal The total on the issue, which may exceed those returned.
	CommentTotal int `json:"comment_total"`

	// Comments Oldest first.
	Comments       []Comment      `json:"comments"`
	Description    string         `json:"description"`
	Key            string         `json:"key"`
	Priority       *string        `json:"priority,omitempty"`
	Reporter       string         `json:"reporter"`
	Status         string         `json:"status"`
	StatusCategory StatusCategory `json:"status_category"`
	Summary        string         `json:"summary"`
	Type           string         `json:"type"`

	// URL The issue in the tracker's own web interface, for a link to open. Empty when the tracker's base URL cannot be read; never carries the base URL's username or password.
	URL string `json:"url"`
}

// IssuesPage defines model for IssuesPage.
type IssuesPage struct {
	Issues []Issue `json:"issues"`

	// StartAt The index of the first issue in this page.
	StartAt int `json:"start_at"`

	// Total How many issues the view matches in all.
	Total int `json:"total"`
}

// JiraConfig defines model for JiraConfig.
type JiraConfig struct {
	BaseURL *string `json:"base_url,omitempty"`

	// Headers Extra request headers; values masked on read.
	Headers *map[string]string `json:"headers,omitempty"`

	// MarkdownComments Post comments written in Markdown as Jira's wiki markup.
	MarkdownComments *bool   `json:"markdown_comments,omitempty"`
	Project          *string `json:"project,omitempty"`

	// ReviewStatus The status an issue moves to once its pull request is open, e.g. "In Review". Empty makes no offer.
	ReviewStatus *string `json:"review_status,omitempty"`

	// Token Masked on read; empty or masked on write keeps the stored value.
	Token        *string     `json:"token,omitempty"`
	TokenCommand *string     `json:"token_command,omitempty"`
	TokenEnv     *string     `json:"token_env,omitempty"`
	User         *string     `json:"user,omitempty"`
	Views        *[]JiraView `json:"views,omitempty"`
}

// JiraView defines model for JiraView.
type JiraView struct {
	Jql  string `json:"jql"`
	Name string `json:"name"`
}

// MessagingConfig defines model for MessagingConfig.
type MessagingConfig struct {
	Announcement *string   `json:"announcement,omitempty"`
	Channel      *string   `json:"channel,omitempty"`
	Channels     *[]string `json:"channels,omitempty"`

	// Kind The service posts go to. Empty is read as slack. It decides the message body and link markup the notifier sends.
	Kind *MessagingConfigKind `json:"kind,omitempty"`

	// Token A Slack bot token. Masked on read; empty or masked on write keeps the stored value. Ignored by the webhook-only kinds.
	Token        *string `json:"token,omitempty"`
	TokenCommand *string `json:"token_command,omitempty"`
	TokenEnv     *string `json:"token_env,omitempty"`

	// WebhookURL A credential; masked on read, preserved on write like a token.
	WebhookURL *string `json:"webhook_url,omitempty"`
}

// MessagingConfigKind The service posts go to. Empty is read as slack. It decides the message body and link markup the notifier sends.
type MessagingConfigKind string

// MessagingDestination defines model for MessagingDestination.
type MessagingDestination struct {
	// Author Who a post would come from; empty if not resolved.
	Author string `json:"author"`

	// Channel The default channel; empty when a webhook carries its own.
	Channel string `json:"channel"`

	// Channels The default first, then the alternates.
	Channels []string `json:"channels"`

	// Configured Whether a transport is set up to post — a bot token or a webhook. A webhook service has no channel, so channel presence cannot stand in for this.
	Configured bool `json:"configured"`

	// Service The service posts go to — Slack, Teams, Discord or webhook.
	Service string `json:"service"`
}

// MovedIssue An issue that was just moved, and the status it is now in.
type MovedIssue struct {
	// Key Example: PROJ-412
	Key string `json:"key"`

	// Status Example: In Review
	Status string `json:"status"`
}

// OpenPullRequestRequest The pull request to open for the checked-out branch.
type OpenPullRequestRequest struct {
	// Assignees Usernames to assign the pull request to.
	Assignees *[]string `json:"assignees,omitempty"`

	// Base The branch to merge into.
	//
	// Example: main
	Base string `json:"base"`

	// Body The pull request body; may be empty.
	Body *string `json:"body,omitempty"`

	// Draft Whether to open it as a draft.
	Draft *bool `json:"draft,omitempty"`

	// Labels Label names to add to the pull request.
	Labels *[]string `json:"labels,omitempty"`

	// Reviewers Usernames to request a review from.
	Reviewers *[]string `json:"reviewers,omitempty"`

	// Title The pull request title.
	//
	// Example: fix: redact tokens before they reach the request log
	Title string `json:"title"`
}

// OpenedPullRequest A pull request that was just opened, with a warning when it opened but its reviewers, assignees or labels could not all be added, and what can be offered next.
type OpenedPullRequest struct {
	// FollowUps What the browser can offer now that the pull request is open, in the order the terminal offers them — the link, then the move. Empty when the branch names no Jira issue, or neither applies.
	FollowUps []FollowUp  `json:"follow_ups"`
	Pull      PullRequest `json:"pull"`

	// Warning Set only when the pull opened but adding its reviewers, assignees or labels did not fully succeed, so a partial success is not reported as a failure.
	Warning *string `json:"warning,omitempty"`
}

// Problem An RFC 9457 problem details object. The detail is safe to show and never carries a secret; code is a stable, machine-readable reason.
type Problem struct {
	// Code A stable, machine-readable reason.
	Code ProblemCode `json:"code"`

	// Detail A human-readable explanation specific to this occurrence.
	Detail string `json:"detail"`

	// Status The HTTP status code.
	Status int `json:"status"`

	// Title A short, human-readable summary of the problem type.
	Title string `json:"title"`

	// Type A URI that identifies the problem type.
	//
	// Example: https://jacob-delgado.github.io/workflow/docs/errors/#not-found
	Type string `json:"type"`
}

// ProblemCode A stable, machine-readable reason.
type ProblemCode string

// PullRequest defines model for PullRequest.
type PullRequest struct {
	Approvals        int                  `json:"approvals"`
	ChangesRequested bool                 `json:"changes_requested"`
	Draft            bool                 `json:"draft"`
	Mergeable        PullRequestMergeable `json:"mergeable"`

	// Number The GitHub number or GitLab IID.
	Number int    `json:"number"`
	Title  string `json:"title"`
	URL    string `json:"url"`
}

// PullRequestMergeable defines model for PullRequest.Mergeable.
type PullRequestMergeable string

// PullRequestConfig defines model for PullRequestConfig.
type PullRequestConfig struct {
	// TitleSource Where a pull request's title comes from: "commit" (the default) takes the branch's oldest commit, "issue" takes the issue it names.
	TitleSource *string `json:"title_source,omitempty"`
}

// PullRequestDraft A pull request composed for the branch, editable before opening.
type PullRequestDraft struct {
	// Base The branch it would merge into.
	Base string `json:"base"`

	// Body The proposed body, from the template, commits, and issue.
	Body string `json:"body"`

	// Draft Whether it would open as a draft; always false in a fresh draft.
	Draft bool `json:"draft"`

	// Head The branch with the work; the open always uses the checked-out one.
	Head string `json:"head"`

	// NeedsPush Whether the branch must be pushed first; the open pushes it.
	NeedsPush bool `json:"needs_push"`

	// Title The proposed title, from the first commit or the issue.
	Title string `json:"title"`
}

// Review defines model for Review.
type Review struct {
	Ci *CI `json:"ci,omitempty"`

	// Found Whether a pull request was found for the branch.
	Found bool         `json:"found"`
	Pull  *PullRequest `json:"pull,omitempty"`
}

// ReviewQueue defines model for ReviewQueue.
type ReviewQueue struct {
	// Available Whether there is a forge to ask. False outside a repository, and when origin is on no forge workflow can read — not GitHub or GitLab, or a self-hosted one forge.kind and forge.host do not name — and requests is then empty.
	Available bool `json:"available"`

	// Requests The open pull or merge requests that ask for your review, the longest-waiting first. Empty when none does, or when there is no forge to ask.
	Requests []ReviewRequest `json:"requests"`
}

// ReviewRequest defines model for ReviewRequest.
type ReviewRequest struct {
	// Author Who opened it, and so who asks for the review.
	Author string  `json:"author"`
	Ci     CIState `json:"ci"`
	Draft  bool    `json:"draft"`

	// Number The GitHub number or GitLab IID.
	Number int `json:"number"`

	// OpenedAt RFC 3339; when it was opened, which is how long it has waited — the zero time if the forge did not give one.
	OpenedAt time.Time `json:"opened_at"`

	// Repository The owner/name (GitHub) or group/project (GitLab) it is in, since the queue spans repositories; empty when the forge did not say.
	//
	// Example: jacob-delgado/workflow
	Repository string `json:"repository"`
	Title      string `json:"title"`
	URL        string `json:"url"`
}

// Snapshot The full read state carried by one event-stream message: everything the cockpit shows, together.
type Snapshot struct {
	Branch Branch `json:"branch"`

	// Branches The local branches named for an issue — the record of what is in flight. The detail panels (branch, changes, review) describe the checked-out branch alone; this lists every issue that has a branch, so the issues list can mark them all in flight, not the one on HEAD.
	Branches  []TaskBranch         `json:"branches"`
	Changes   ChangeList           `json:"changes"`
	Issues    IssuesPage           `json:"issues"`
	Messaging MessagingDestination `json:"messaging"`
	Review    Review               `json:"review"`

	// SuggestedScope The scope a new commit opens on — the terminal composer's rule: the scope last committed with in this repository, else commit.default_scope, else empty. The server reads the learned one from its store once, and once more after a commit here records one, not on every message, and never under --dry-run, when the default alone applies.
	//
	// Example: api
	SuggestedScope string `json:"suggested_scope"`
}

// StagingRequest What to stage or unstage: one changed file, or all of them — one or the other, never both.
type StagingRequest struct {
	// All Every change: for staging, each one the index does not hold yet; for unstaging, each staged one.
	All *bool `json:"all,omitempty"`

	// Path A changed file, by the path the working tree's changes list it under (a rename's new path).
	//
	// Example: internal/config/config.go
	Path *string `json:"path,omitempty"`
}

// StatusCategory defines model for StatusCategory.
type StatusCategory string

// StoreConfig defines model for StoreConfig.
type StoreConfig struct {
	// Disabled Turn off the on-disk store, keeping nothing between sessions. Off by default: the store is on and never holds a secret.
	Disabled *bool `json:"disabled,omitempty"`
}

// TaskBranch A local branch named for an issue, by the branch-name convention.
type TaskBranch struct {
	// Current Whether this is the checked-out branch.
	Current bool `json:"current"`

	// IssueKey The issue the branch is named for — a Jira key or a forge issue number, per the branch-name convention.
	//
	// Example: PROJ-412
	IssueKey string `json:"issue_key"`

	// Name The local branch name.
	//
	// Example: fix/PROJ-412-redact-tokens
	Name string `json:"name"`
}

// TimingConfig defines model for TimingConfig.
type TimingConfig struct {
	// CiInterval A Go duration; empty for the default.
	CiInterval *string `json:"ci_interval,omitempty"`

	// RequestTimeout A Go duration such as 20s; empty for the default.
	RequestTimeout *string `json:"request_timeout,omitempty"`
}

// UIConfig defines model for UIConfig.
type UIConfig struct {
	ASCII *bool `json:"ascii,omitempty"`

	// Color Empty for auto, or "never".
	Color *string `json:"color,omitempty"`

	// CommentsShown How many comments the detail shows; 0 means the built-in default.
	CommentsShown *int `json:"comments_shown,omitempty"`

	// Keys Map from a key action to the key that triggers it; see the configuration docs for the actions.
	Keys   *map[string]string `json:"keys,omitempty"`
	Mouse  *bool              `json:"mouse,omitempty"`
	Notify *bool              `json:"notify,omitempty"`
}

// ViewList defines model for ViewList.
type ViewList struct {
	Views []JiraView `json:"views"`
}

// StreamEventsParams defines parameters for StreamEvents.
type StreamEventsParams struct {
	// View The configured view's name whose issues to include; the default view when omitted.
	View *string `form:"view,omitempty" json:"view,omitempty"`
}

// ListIssuesParams defines parameters for ListIssues.
type ListIssuesParams struct {
	// View The configured view's name; the default view when omitted.
	View *string `form:"view,omitempty" json:"view,omitempty"`

	// StartAt The zero-based index of the first issue to return.
	StartAt *int `form:"start_at,omitempty" json:"start_at,omitempty"`
}

// AnnounceJSONRequestBody defines body for Announce for application/json ContentType.
type AnnounceJSONRequestBody = AnnounceRequest

// CreateBranchJSONRequestBody defines body for CreateBranch for application/json ContentType.
type CreateBranchJSONRequestBody = CreateBranchRequest

// CheckoutJSONRequestBody defines body for Checkout for application/json ContentType.
type CheckoutJSONRequestBody = CheckoutRequest

// CommitJSONRequestBody defines body for Commit for application/json ContentType.
type CommitJSONRequestBody = CommitRequest

// UpdateConfigJSONRequestBody defines body for UpdateConfig for application/json ContentType.
type UpdateConfigJSONRequestBody = Config

// OpenPullRequestJSONRequestBody defines body for OpenPullRequest for application/json ContentType.
type OpenPullRequestJSONRequestBody = OpenPullRequestRequest

// StageJSONRequestBody defines body for Stage for application/json ContentType.
type StageJSONRequestBody = StagingRequest

// UnstageJSONRequestBody defines body for Unstage for application/json ContentType.
type UnstageJSONRequestBody = StagingRequest
