// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for ActivitySourceName.
const (
	ActivitySourceNameForge ActivitySourceName = "forge"
	ActivitySourceNameGit   ActivitySourceName = "git"
	ActivitySourceNameJira  ActivitySourceName = "jira"
	ActivitySourceNameTasks ActivitySourceName = "tasks"
)

// Valid indicates whether the value is a known member of the ActivitySourceName enum.
func (e ActivitySourceName) Valid() bool {
	switch e {
	case ActivitySourceNameForge:
		return true
	case ActivitySourceNameGit:
		return true
	case ActivitySourceNameJira:
		return true
	case ActivitySourceNameTasks:
		return true
	default:
		return false
	}
}

// Defines values for ActivitySourceState.
const (
	ActivitySourceFailed   ActivitySourceState = "failed"
	ActivitySourceNotSetUp ActivitySourceState = "not_set_up"
	ActivitySourceRead     ActivitySourceState = "read"
)

// Valid indicates whether the value is a known member of the ActivitySourceState enum.
func (e ActivitySourceState) Valid() bool {
	switch e {
	case ActivitySourceFailed:
		return true
	case ActivitySourceNotSetUp:
		return true
	case ActivitySourceRead:
		return true
	default:
		return false
	}
}

// Defines values for AnnounceRequestWhen.
const (
	AnnounceNow          AnnounceRequestWhen = "now"
	AnnounceWhenCIPasses AnnounceRequestWhen = "ci_passes"
)

// Valid indicates whether the value is a known member of the AnnounceRequestWhen enum.
func (e AnnounceRequestWhen) Valid() bool {
	switch e {
	case AnnounceNow:
		return true
	case AnnounceWhenCIPasses:
		return true
	default:
		return false
	}
}

// Defines values for CIState.
const (
	Failed  CIState = "failed"
	None    CIState = "none"
	Passed  CIState = "passed"
	Running CIState = "running"
)

// Valid indicates whether the value is a known member of the CIState enum.
func (e CIState) Valid() bool {
	switch e {
	case Failed:
		return true
	case None:
		return true
	case Passed:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for ChangeKind.
const (
	ChangeKindConflicted ChangeKind = "conflicted"
	ChangeKindCopied     ChangeKind = "copied"
	ChangeKindDeleted    ChangeKind = "deleted"
	ChangeKindModified   ChangeKind = "modified"
	ChangeKindNew        ChangeKind = "new"
	ChangeKindRenamed    ChangeKind = "renamed"
	ChangeKindUntracked  ChangeKind = "untracked"
)

// Valid indicates whether the value is a known member of the ChangeKind enum.
func (e ChangeKind) Valid() bool {
	switch e {
	case ChangeKindConflicted:
		return true
	case ChangeKindCopied:
		return true
	case ChangeKindDeleted:
		return true
	case ChangeKindModified:
		return true
	case ChangeKindNew:
		return true
	case ChangeKindRenamed:
		return true
	case ChangeKindUntracked:
		return true
	default:
		return false
	}
}

// Defines values for FavoriteState.
const (
	FavoriteDirectory  FavoriteState = "directory"
	FavoriteHere       FavoriteState = "here"
	FavoriteMissing    FavoriteState = "missing"
	FavoriteRepository FavoriteState = "repository"
)

// Valid indicates whether the value is a known member of the FavoriteState enum.
func (e FavoriteState) Valid() bool {
	switch e {
	case FavoriteDirectory:
		return true
	case FavoriteHere:
		return true
	case FavoriteMissing:
		return true
	case FavoriteRepository:
		return true
	default:
		return false
	}
}

// Defines values for FollowUpAction.
const (
	Link       FollowUpAction = "link"
	Transition FollowUpAction = "transition"
)

// Valid indicates whether the value is a known member of the FollowUpAction enum.
func (e FollowUpAction) Valid() bool {
	switch e {
	case Link:
		return true
	case Transition:
		return true
	default:
		return false
	}
}

// Defines values for ForgeConfigKind.
const (
	ForgeConfigKindEmpty  ForgeConfigKind = ""
	ForgeConfigKindGithub ForgeConfigKind = "github"
	ForgeConfigKindGitlab ForgeConfigKind = "gitlab"
)

// Valid indicates whether the value is a known member of the ForgeConfigKind enum.
func (e ForgeConfigKind) Valid() bool {
	switch e {
	case ForgeConfigKindEmpty:
		return true
	case ForgeConfigKindGithub:
		return true
	case ForgeConfigKindGitlab:
		return true
	default:
		return false
	}
}

// Defines values for IssueTracker.
const (
	IssueTrackerForge IssueTracker = "forge"
	IssueTrackerJira  IssueTracker = "jira"
)

// Valid indicates whether the value is a known member of the IssueTracker enum.
func (e IssueTracker) Valid() bool {
	switch e {
	case IssueTrackerForge:
		return true
	case IssueTrackerJira:
		return true
	default:
		return false
	}
}

// Defines values for LinkedIssueOrigin.
const (
	LinkedIssueOriginBranchName  LinkedIssueOrigin = "branch_name"
	LinkedIssueOriginByHand      LinkedIssueOrigin = "by_hand"
	LinkedIssueOriginPullRequest LinkedIssueOrigin = "pull_request"
)

// Valid indicates whether the value is a known member of the LinkedIssueOrigin enum.
func (e LinkedIssueOrigin) Valid() bool {
	switch e {
	case LinkedIssueOriginBranchName:
		return true
	case LinkedIssueOriginByHand:
		return true
	case LinkedIssueOriginPullRequest:
		return true
	default:
		return false
	}
}

// Defines values for LocalDataFileKind.
const (
	LocalDataFileKindCache LocalDataFileKind = "cache"
	LocalDataFileKindKept  LocalDataFileKind = "kept"
)

// Valid indicates whether the value is a known member of the LocalDataFileKind enum.
func (e LocalDataFileKind) Valid() bool {
	switch e {
	case LocalDataFileKindCache:
		return true
	case LocalDataFileKindKept:
		return true
	default:
		return false
	}
}

// Defines values for MergeMethod.
const (
	MergeMethodMerge  MergeMethod = "merge"
	MergeMethodRebase MergeMethod = "rebase"
	MergeMethodSquash MergeMethod = "squash"
)

// Valid indicates whether the value is a known member of the MergeMethod enum.
func (e MergeMethod) Valid() bool {
	switch e {
	case MergeMethodMerge:
		return true
	case MergeMethodRebase:
		return true
	case MergeMethodSquash:
		return true
	default:
		return false
	}
}

// Defines values for MessagingConfigKind.
const (
	MessagingConfigKindDiscord MessagingConfigKind = "discord"
	MessagingConfigKindEmpty   MessagingConfigKind = ""
	MessagingConfigKindSlack   MessagingConfigKind = "slack"
	MessagingConfigKindTeams   MessagingConfigKind = "teams"
	MessagingConfigKindWebhook MessagingConfigKind = "webhook"
)

// Valid indicates whether the value is a known member of the MessagingConfigKind enum.
func (e MessagingConfigKind) Valid() bool {
	switch e {
	case MessagingConfigKindDiscord:
		return true
	case MessagingConfigKindEmpty:
		return true
	case MessagingConfigKindSlack:
		return true
	case MessagingConfigKindTeams:
		return true
	case MessagingConfigKindWebhook:
		return true
	default:
		return false
	}
}

// Defines values for OwnerTagKind.
const (
	Team OwnerTagKind = "team"
	User OwnerTagKind = "user"
)

// Valid indicates whether the value is a known member of the OwnerTagKind enum.
func (e OwnerTagKind) Valid() bool {
	switch e {
	case Team:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for OwnerTagState.
const (
	Linked     OwnerTagState = "linked"
	NotOnSlack OwnerTagState = "not_on_slack"
	Unlinked   OwnerTagState = "unlinked"
)

// Valid indicates whether the value is a known member of the OwnerTagState enum.
func (e OwnerTagState) Valid() bool {
	switch e {
	case Linked:
		return true
	case NotOnSlack:
		return true
	case Unlinked:
		return true
	default:
		return false
	}
}

// Defines values for PostLengthUnit.
const (
	Bytes      PostLengthUnit = "bytes"
	Characters PostLengthUnit = "characters"
)

// Valid indicates whether the value is a known member of the PostLengthUnit enum.
func (e PostLengthUnit) Valid() bool {
	switch e {
	case Bytes:
		return true
	case Characters:
		return true
	default:
		return false
	}
}

// Defines values for ProblemCode.
const (
	BadRequest           ProblemCode = "bad_request"
	CheckFailed          ProblemCode = "check_failed"
	Conflict             ProblemCode = "conflict"
	FetchFailed          ProblemCode = "fetch_failed"
	Internal             ProblemCode = "internal"
	MethodNotAllowed     ProblemCode = "method_not_allowed"
	NotFound             ProblemCode = "not_found"
	NotSetUp             ProblemCode = "not_set_up"
	PreconditionRequired ProblemCode = "precondition_required"
	TooLong              ProblemCode = "too_long"
	Unprocessable        ProblemCode = "unprocessable"
	Unreachable          ProblemCode = "unreachable"
)

// Valid indicates whether the value is a known member of the ProblemCode enum.
func (e ProblemCode) Valid() bool {
	switch e {
	case BadRequest:
		return true
	case CheckFailed:
		return true
	case Conflict:
		return true
	case FetchFailed:
		return true
	case Internal:
		return true
	case MethodNotAllowed:
		return true
	case NotFound:
		return true
	case NotSetUp:
		return true
	case PreconditionRequired:
		return true
	case TooLong:
		return true
	case Unprocessable:
		return true
	case Unreachable:
		return true
	default:
		return false
	}
}

// Defines values for PullRequestMergeable.
const (
	Clean     PullRequestMergeable = "clean"
	Conflicts PullRequestMergeable = "conflicts"
	Unknown   PullRequestMergeable = "unknown"
)

// Valid indicates whether the value is a known member of the PullRequestMergeable enum.
func (e PullRequestMergeable) Valid() bool {
	switch e {
	case Clean:
		return true
	case Conflicts:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for PullRequestState.
const (
	Closed PullRequestState = "closed"
	Merged PullRequestState = "merged"
	Open   PullRequestState = "open"
)

// Valid indicates whether the value is a known member of the PullRequestState enum.
func (e PullRequestState) Valid() bool {
	switch e {
	case Closed:
		return true
	case Merged:
		return true
	case Open:
		return true
	default:
		return false
	}
}

// Defines values for QueuedAnnouncementState.
const (
	QueuedAnnounced  QueuedAnnouncementState = "announced"
	QueuedAnnouncing QueuedAnnouncementState = "announcing"
	QueuedDropped    QueuedAnnouncementState = "dropped"
	QueuedWaiting    QueuedAnnouncementState = "waiting"
)

// Valid indicates whether the value is a known member of the QueuedAnnouncementState enum.
func (e QueuedAnnouncementState) Valid() bool {
	switch e {
	case QueuedAnnounced:
		return true
	case QueuedAnnouncing:
		return true
	case QueuedDropped:
		return true
	case QueuedWaiting:
		return true
	default:
		return false
	}
}

// Defines values for RunState.
const (
	InProgress RunState = "in_progress"
	Refused    RunState = "refused"
	Stopped    RunState = "stopped"
	Succeeded  RunState = "succeeded"
)

// Valid indicates whether the value is a known member of the RunState enum.
func (e RunState) Valid() bool {
	switch e {
	case InProgress:
		return true
	case Refused:
		return true
	case Stopped:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// Defines values for RunKind.
const (
	RunKindAmend     RunKind = "amend"
	RunKindFixup     RunKind = "fixup"
	RunKindPreCommit RunKind = "pre_commit"
	RunKindRebase    RunKind = "rebase"
)

// Valid indicates whether the value is a known member of the RunKind enum.
func (e RunKind) Valid() bool {
	switch e {
	case RunKindAmend:
		return true
	case RunKindFixup:
		return true
	case RunKindPreCommit:
		return true
	case RunKindRebase:
		return true
	default:
		return false
	}
}

// Defines values for SetupPlaceName.
const (
	Home       SetupPlaceName = "home"
	Repository SetupPlaceName = "repository"
)

// Valid indicates whether the value is a known member of the SetupPlaceName enum.
func (e SetupPlaceName) Valid() bool {
	switch e {
	case Home:
		return true
	case Repository:
		return true
	default:
		return false
	}
}

// Defines values for StatusCategory.
const (
	StatusCategoryDone          StatusCategory = "done"
	StatusCategoryIndeterminate StatusCategory = "indeterminate"
	StatusCategoryNew           StatusCategory = "new"
)

// Valid indicates whether the value is a known member of the StatusCategory enum.
func (e StatusCategory) Valid() bool {
	switch e {
	case StatusCategoryDone:
		return true
	case StatusCategoryIndeterminate:
		return true
	case StatusCategoryNew:
		return true
	default:
		return false
	}
}

// Defines values for StatusChangeFieldKind.
const (
	FieldDateKind       StatusChangeFieldKind = "date"
	FieldOnlyJiraKind   StatusChangeFieldKind = "only_jira"
	FieldOptionKind     StatusChangeFieldKind = "option"
	FieldOptionListKind StatusChangeFieldKind = "option_list"
	FieldTextKind       StatusChangeFieldKind = "text"
	FieldUserKind       StatusChangeFieldKind = "user"
)

// Valid indicates whether the value is a known member of the StatusChangeFieldKind enum.
func (e StatusChangeFieldKind) Valid() bool {
	switch e {
	case FieldDateKind:
		return true
	case FieldOnlyJiraKind:
		return true
	case FieldOptionKind:
		return true
	case FieldOptionListKind:
		return true
	case FieldTextKind:
		return true
	case FieldUserKind:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	TaskStatusCompleted TaskStatus = "completed"
	TaskStatusDeleted   TaskStatus = "deleted"
	TaskStatusPending   TaskStatus = "pending"
	TaskStatusRecurring TaskStatus = "recurring"
	TaskStatusWaiting   TaskStatus = "waiting"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusCompleted:
		return true
	case TaskStatusDeleted:
		return true
	case TaskStatusPending:
		return true
	case TaskStatusRecurring:
		return true
	case TaskStatusWaiting:
		return true
	default:
		return false
	}
}

// Defines values for TaskListReasonCode.
const (
	MalformedTaskrc TaskListReasonCode = "malformed_taskrc"
	NeverRun        TaskListReasonCode = "never_run"
	NotInstalled    TaskListReasonCode = "not_installed"
	NotTaskwarrior  TaskListReasonCode = "not_taskwarrior"
	TooOld          TaskListReasonCode = "too_old"
	TurnedOff       TaskListReasonCode = "turned_off"
	Unavailable     TaskListReasonCode = "unavailable"
)

// Valid indicates whether the value is a known member of the TaskListReasonCode enum.
func (e TaskListReasonCode) Valid() bool {
	switch e {
	case MalformedTaskrc:
		return true
	case NeverRun:
		return true
	case NotInstalled:
		return true
	case NotTaskwarrior:
		return true
	case TooOld:
		return true
	case TurnedOff:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for UIConfigColor.
const (
	UIConfigColorEmpty UIConfigColor = ""
	UIConfigColorNever UIConfigColor = "never"
)

// Valid indicates whether the value is a known member of the UIConfigColor enum.
func (e UIConfigColor) Valid() bool {
	switch e {
	case UIConfigColorEmpty:
		return true
	case UIConfigColorNever:
		return true
	default:
		return false
	}
}

// Defines values for WorktreeState.
const (
	WorktreeHere    WorktreeState = "here"
	WorktreeMissing WorktreeState = "missing"
	WorktreeOther   WorktreeState = "worktree"
)

// Valid indicates whether the value is a known member of the WorktreeState enum.
func (e WorktreeState) Valid() bool {
	switch e {
	case WorktreeHere:
		return true
	case WorktreeMissing:
		return true
	case WorktreeOther:
		return true
	default:
		return false
	}
}

// Defines values for RemoveLocalDataParamsScope.
const (
	RemoveLocalDataParamsScopeAll   RemoveLocalDataParamsScope = "all"
	RemoveLocalDataParamsScopeCache RemoveLocalDataParamsScope = "cache"
)

// Valid indicates whether the value is a known member of the RemoveLocalDataParamsScope enum.
func (e RemoveLocalDataParamsScope) Valid() bool {
	switch e {
	case RemoveLocalDataParamsScopeAll:
		return true
	case RemoveLocalDataParamsScopeCache:
		return true
	default:
		return false
	}
}

// Activity defines model for Activity.
type Activity struct {
	// From The period's first day, YYYY-MM-DD.
	From string `json:"from"`

	// PostLength How long the summary's text is once rendered for the messaging service set up, as that service measures it, against the most it takes. Left out where no messaging is set up, or where the service names no limit (a plain webhook). A post longer than the limit is refused with too_long, and nothing is sent.
	PostLength *PostLength `json:"post_length,omitempty"`

	// Sources Each source asked, in a fixed order, and how its read went.
	Sources []ActivitySource `json:"sources"`

	// Text The summary as Markdown, ready to copy.
	Text string `json:"text"`

	// To The period's last day, YYYY-MM-DD.
	To string `json:"to"`

	// Today The day it is where the server runs, YYYY-MM-DD, so a later period is not offered.
	Today string         `json:"today"`
	Years []ActivityYear `json:"years"`
}

// ActivityDay defines model for ActivityDay.
type ActivityDay struct {
	// Date The day, YYYY-MM-DD.
	Date  string         `json:"date"`
	Hours []ActivityHour `json:"hours"`

	// Weekday The day of the week, such as Friday.
	Weekday string `json:"weekday"`
}

// ActivityHour defines model for ActivityHour.
type ActivityHour struct {
	Items []ActivityItem `json:"items"`

	// Label The hour as the clock showed it, such as 09:00, with its zone added when the clocks showed it twice that day.
	Label string `json:"label"`
}

// ActivityItem defines model for ActivityItem.
type ActivityItem struct {
	At time.Time `json:"at"`

	// Ref What it was done to, such as a commit's hash, PROJ-412 or o/r#42.
	Ref        string `json:"ref"`
	Repository string `json:"repository"`

	// Source A place work leaves a trace.
	Source ActivitySourceName `json:"source"`
	Title  string             `json:"title"`

	// URL A link to it, or empty where there is none.
	URL string `json:"url"`

	// Verb What was done, such as "committed" or "moved".
	Verb string `json:"verb"`
}

// ActivityMonth defines model for ActivityMonth.
type ActivityMonth struct {
	Days  []ActivityDay `json:"days"`
	Month int           `json:"month"`

	// Name The month's name, such as October.
	Name string `json:"name"`
}

// ActivityPost A Summary as it was posted.
type ActivityPost struct {
	// Channel The channel it was posted to, or empty for a webhook's own channel.
	Channel string `json:"channel"`

	// Destination Where it went, in words: the channel, or the channel its webhook is bound to.
	Destination string `json:"destination"`

	// From The period's first day, YYYY-MM-DD.
	From string `json:"from"`

	// Text The Markdown posted, before it was rendered for the service.
	Text string `json:"text"`

	// To The period's last day, YYYY-MM-DD.
	To string `json:"to"`
}

// ActivityPostRequest The period a Summary is of, its Markdown to post, and where.
type ActivityPostRequest struct {
	// Channel The channel to post to; empty or left out uses the configured channel or the webhook.
	Channel *string `json:"channel,omitempty"`

	// From The period's first day, YYYY-MM-DD.
	From string `json:"from"`

	// Text The Summary's Markdown, as GET /api/activity wrote it or as it was edited.
	Text string `json:"text"`

	// To The period's last day, YYYY-MM-DD.
	To string `json:"to"`
}

// ActivitySource defines model for ActivitySource.
type ActivitySource struct {
	// Detail Why the source is not set up and how to set it up, or why it could not be read, in words that never name a host or a path; empty when it was read. When several repositories were read, each that could not be is named in its own clause.
	Detail string `json:"detail"`

	// Name The source as a sentence starts with it, such as "Jira".
	Name string `json:"name"`

	// Source A place work leaves a trace.
	Source ActivitySourceName `json:"source"`

	// State How the source answered: read; not_set_up, when there was nothing set up to ask — no credential, no forge the origin names, no Taskwarrior installed, no git user.email — so it was left out; or failed, when a source that is set up was asked and could not be read.
	State ActivitySourceState `json:"state"`

	// Truncated The source had more than it gave.
	Truncated bool `json:"truncated"`
}

// ActivitySourceName A place work leaves a trace.
type ActivitySourceName string

// ActivitySourceState How the source answered: read; not_set_up, when there was nothing set up to ask — no credential, no forge the origin names, no Taskwarrior installed, no git user.email — so it was left out; or failed, when a source that is set up was asked and could not be read.
type ActivitySourceState string

// ActivityYear defines model for ActivityYear.
type ActivityYear struct {
	Months []ActivityMonth `json:"months"`
	Year   int             `json:"year"`
}

// AnnounceMentions Whom to tag with the post. The linked user owners are tagged from what is kept, not from the request; users are the ones the preview showed tagged, so a post whose kept links changed since is refused rather than tagging someone else. groups name the user groups checked, each one the announcement offered.
type AnnounceMentions struct {
	Groups []string `json:"groups"`
	Users  []string `json:"users"`
}

// AnnounceRequest Where to post the announcement, the text its preview showed, the text to post in its place when it was edited, and when to post it.
type AnnounceRequest struct {
	// Channel The channel to post to; empty uses the configured channel or the webhook.
	Channel string `json:"channel"`

	// EditedText The text to post in place of the composed announcement, as edited in the preview. It needs text, the composed announcement the edit began from, which is still checked against the one composed now.
	EditedText *string `json:"edited_text,omitempty"`

	// Mentions Whom to tag with the post. The linked user owners are tagged from what is kept, not from the request; users are the ones the preview showed tagged, so a post whose kept links changed since is refused rather than tagging someone else. groups name the user groups checked, each one the announcement offered.
	Mentions *AnnounceMentions `json:"mentions,omitempty"`

	// Text The announcement as GET /api/announcement showed it. When given, the post is refused with 409 unless the announcement composed now reads the same; when left out, the announcement composed now is posted.
	Text *string `json:"text,omitempty"`

	// When now, the default, posts at once; ci_passes holds a ready-for-review announcement until the pull request's CI passes.
	When *AnnounceRequestWhen `json:"when,omitempty"`
}

// AnnounceRequestWhen now, the default, posts at once; ci_passes holds a ready-for-review announcement until the pull request's CI passes.
type AnnounceRequestWhen string

// Announcement A composed announcement and where it would post.
type Announcement struct {
	// CanWaitForCi Whether a preview's announcement can be held until the pull request's CI passes: it is ready for review and its CI is still running. Left out where it cannot, and on a post.
	CanWaitForCi *bool `json:"can_wait_for_ci,omitempty"`

	// Channel The channel it posts to, or empty for a webhook's own channel.
	Channel string `json:"channel"`

	// Tagging Whom a ready-for-review announcement proposes to tag on Slack: the code owners of the branch's changes, and the user groups it offers.
	Tagging *AnnouncementTagging `json:"tagging,omitempty"`

	// Text The message that would be posted.
	Text string `json:"text"`
}

// AnnouncementTagging Whom a ready-for-review announcement proposes to tag on Slack: the code owners of the branch's changes, and the user groups it offers.
type AnnouncementTagging struct {
	// Available Whether this announcement can tag anyone: only a ready-for-review announcement does, and only with the store on. When false, owners and groups are empty.
	Available bool       `json:"available"`
	Groups    []GroupTag `json:"groups"`

	// MissingScope A scope the Slack token lacks to offer the people or groups an owner not yet linked could be linked to, such as users:read. The announcement still posts, tagging whom it can.
	//
	// Example: usergroups:read
	MissingScope *string    `json:"missing_scope,omitempty"`
	Owners       []OwnerTag `json:"owners"`

	// UnavailableReason Why this announcement tags no one though it would: the Slack workspace the token is for could not be read, and links are kept per workspace. The announcement posts untagged; available is false and owners and groups are empty.
	//
	// Example: can't tell which Slack workspace this token is for: the credential was not accepted
	UnavailableReason *string `json:"unavailable_reason,omitempty"`
}

// AssignRequest Whom to assign an issue to.
type AssignRequest struct {
	// Assignee The username, as the issue's tracker knows it.
	Assignee string `json:"assignee"`
}

// AssignedIssue An issue just assigned, and to whom.
type AssignedIssue struct {
	// Assignee Example: ana.lopez
	Assignee string `json:"assignee"`

	// Key Example: PROJ-412
	Key string `json:"key"`
}

// Branch defines model for Branch.
type Branch struct {
	Ahead int `json:"ahead"`

	// Base The base branch, such as origin/main.
	Base   string `json:"base"`
	Behind int    `json:"behind"`

	// Commits The commits on this branch since its base.
	Commits []Commit `json:"commits"`

	// Detached Whether HEAD is detached rather than on a branch.
	Detached bool `json:"detached"`

	// Head The commit SHA; empty before the first commit, and in a write's answer when the branch could not be read back after the write landed.
	Head string `json:"head"`

	// IssueLink The issue the branch was linked to by hand, for work begun outside workflow; empty when it was never linked.
	IssueLink string `json:"issue_link"`
	Name      string `json:"name"`

	// PushRemote The remote a push of the branch goes to: remote.pushDefault when the repository sets one, origin otherwise.
	PushRemote string `json:"push_remote"`

	// Upstream The tracking branch; empty if never pushed.
	Upstream string `json:"upstream"`
}

// BranchConfig defines model for BranchConfig.
type BranchConfig struct {
	DefaultPrefix *string            `json:"default_prefix,omitempty"`
	Prefixes      *map[string]string `json:"prefixes,omitempty"`

	// SlugLimit The summary slug's length cap in a branch name; zero keeps 48.
	SlugLimit *int `json:"slug_limit,omitempty"`

	// Template The branch-name template; must contain {key}.
	Template *string `json:"template,omitempty"`
}

// BranchIssuePreview defines model for BranchIssuePreview.
type BranchIssuePreview struct {
	// Body Its description as linking would leave it.
	Body string `json:"body"`

	// Changes Whether linking would change the description at all.
	Changes bool `json:"changes"`

	// Key The issue's key, a forge number without its
	Key string `json:"key"`

	// Pull The open pull request's number, or 0 when the branch has none.
	Pull int `json:"pull"`
}

// BranchIssueRequest defines model for BranchIssueRequest.
type BranchIssueRequest struct {
	// Key A Jira key, or a forge issue number with or without its
	//
	// Example: PROJ-412
	Key string `json:"key"`

	// UpdatePull Add the line naming the issue to the open pull request's description.
	UpdatePull bool `json:"update_pull"`
}

// CI defines model for CI.
type CI struct {
	Checks []Check `json:"checks"`
	Done   int     `json:"done"`
	Failed int     `json:"failed"`
	State  CIState `json:"state"`

	// Total Total checks; 0 on a forge that reports the pipeline whole.
	Total int `json:"total"`
}

// CIState defines model for CIState.
type CIState string

// Change defines model for Change.
type Change struct {
	Conflicted bool `json:"conflicted"`

	// HasUnstaged Whether there are unstaged edits to the same path.
	HasUnstaged bool `json:"has_unstaged"`

	// Kind What kind of change this is.
	Kind ChangeKind `json:"kind"`

	// OriginalPath The former path for a rename or copy; absent otherwise.
	OriginalPath *string `json:"original_path,omitempty"`
	Path         string  `json:"path"`

	// Staged Whether the change (or part of it) is staged.
	Staged bool `json:"staged"`
}

// ChangeKind What kind of change this is.
type ChangeKind string

// ChangeList defines model for ChangeList.
type ChangeList struct {
	Changes []Change `json:"changes"`
}

// Check defines model for Check.
type Check struct {
	// ID The forge's own id for the check, so its log can be asked for; absent for a status.
	ID *string `json:"id,omitempty"`

	// LogAvailable Whether the forge serves the check's log.
	LogAvailable *bool  `json:"log_available,omitempty"`
	Name         string `json:"name"`

	// Reason Why a failed check failed, in the forge's few words; absent when it gives none.
	Reason *string `json:"reason,omitempty"`

	// Stage The pipeline stage a GitLab job ran in; absent on GitHub.
	Stage *string `json:"stage,omitempty"`
	State CIState `json:"state"`
	URL   string  `json:"url"`
}

// CheckoutRequest The branch to check out.
type CheckoutRequest struct {
	// Branch The local branch to switch the working tree to.
	//
	// Example: fix/PROJ-412-redact-tokens
	Branch string `json:"branch"`
}

// Comment defines model for Comment.
type Comment struct {
	Author string `json:"author"`
	Body   string `json:"body"`

	// Created RFC 3339; the zero time if the tracker's date was unreadable.
	Created time.Time `json:"created"`
}

// CommentRequest A comment to post on an issue.
type CommentRequest struct {
	// Text The comment, written as Markdown when jira.markdown_comments is on as last saved, and as Jira wiki markup otherwise.
	Text string `json:"text"`
}

// Commit defines model for Commit.
type Commit struct {
	Hash    string `json:"hash"`
	Subject string `json:"subject"`

	// Unpushed Whether the commit is one not yet pushed, which alone staged changes can be amended or fixed up into. A branch with more commits than are read marks none.
	Unpushed bool `json:"unpushed"`
}

// CommitConfig defines model for CommitConfig.
type CommitConfig struct {
	DefaultScope *string `json:"default_scope,omitempty"`

	// RefsTrailer The issue trailer's label, such as "Closes"; empty keeps "Refs".
	RefsTrailer *string `json:"refs_trailer,omitempty"`

	// SubjectLimit The longest a subject may be, in characters; zero keeps 72.
	SubjectLimit *int `json:"subject_limit,omitempty"`

	// Types The commit types the composer offers and validates against, in order; empty keeps the built-in Conventional Commit types.
	Types *[]string `json:"types,omitempty"`
}

// CommitRequest The parts of a Conventional Commit message for the staged changes.
type CommitRequest struct {
	// Body The optional message body, after a blank line.
	Body *string `json:"body,omitempty"`

	// Breaking Whether this is a breaking change, marked with "!".
	Breaking *bool `json:"breaking,omitempty"`

	// Scope The optional scope, written in parentheses after the type.
	Scope *string `json:"scope,omitempty"`

	// Subject The description written after the colon.
	//
	// Example: redact tokens before they reach the request log
	Subject string `json:"subject"`

	// Type The Conventional Commit type, such as feat or fix.
	//
	// Example: fix
	Type string `json:"type"`
}

// Config The whole configuration file. On a read, the six secret fields and the Jira header values are masked; on a write, a masked or empty secret keeps the stored value.
type Config struct {
	Branch      BranchConfig      `json:"branch"`
	Commit      CommitConfig      `json:"commit"`
	Forge       ForgeConfig       `json:"forge"`
	Issues      IssuesConfig      `json:"issues"`
	Jira        JiraConfig        `json:"jira"`
	Messaging   MessagingConfig   `json:"messaging"`
	PullRequest PullRequestConfig `json:"pull_request"`
	Store       StoreConfig       `json:"store"`
	Taskwarrior TaskwarriorConfig `json:"taskwarrior"`
	Timing      TimingConfig      `json:"timing"`
	UI          UIConfig          `json:"ui"`
	Version     string            `json:"version"`
}

// CreateBranchRequest The issue to start work on by creating its branch.
type CreateBranchRequest struct {
	// Fetch Whether to fetch origin first, so the branch starts from what origin holds now, as the terminal's branch creator and workflow branch --fetch do. A fetch that fails creates nothing and is a 502 with code fetch_failed; asking again with fetch false branches from what you have, the terminal's way out. With no base to refresh nothing is fetched either way.
	Fetch *bool `json:"fetch,omitempty"`

	// IssueKey The issue to name and create a branch for.
	//
	// Example: PROJ-412
	IssueKey string `json:"issue_key"`
}

// CreateWorktreeRequest The issue to start work on in a new worktree.
type CreateWorktreeRequest struct {
	// Fetch Whether to fetch origin first, so the branch starts from what origin holds now, as the terminal's branch creator and workflow branch --fetch do. A fetch that fails creates nothing and is a 502 with code fetch_failed; asking again with fetch false branches from what you have, the terminal's way out. With no base to refresh nothing is fetched either way.
	Fetch *bool `json:"fetch,omitempty"`

	// IssueKey The issue to name and create a branch for.
	//
	// Example: PROJ-412
	IssueKey string `json:"issue_key"`
}

// CreatedWorktree A worktree just created for an issue's branch.
type CreatedWorktree struct {
	// Branch The branch created and checked out there.
	Branch string `json:"branch"`

	// Dir The worktree's directory, as an absolute path.
	Dir string `json:"dir"`

	// Shown The directory written from your home.
	Shown string `json:"shown"`
}

// DirectoryChoice A directory, as an absolute path.
type DirectoryChoice struct {
	Dir string `json:"dir"`
}

// DirectoryEntry A directory in another.
type DirectoryEntry struct {
	Name string `json:"name"`

	// Path The directory, as an absolute path.
	Path string `json:"path"`

	// Repository Whether it is a repository's root.
	Repository bool `json:"repository"`
}

// DirectoryListing A directory and the directories in it, by name.
type DirectoryListing struct {
	Entries []DirectoryEntry `json:"entries"`

	// Parent The directory above it, or empty at the root.
	Parent string `json:"parent"`

	// Path The directory listed, as an absolute path.
	Path string `json:"path"`

	// Shown The directory written from your home.
	Shown string `json:"shown"`

	// Truncated Whether there were more than a thousand.
	Truncated bool `json:"truncated"`
}

// DiscardRequest The one changed file whose changes to discard.
type DiscardRequest struct {
	// Path A changed file, by the path the working tree's changes list it under (a rename's new path).
	//
	// Example: internal/config/config.go
	Path string `json:"path"`
}

// Favorite A directory you keep as a favorite, and what is there now.
type Favorite struct {
	// Dir The directory, as an absolute path.
	Dir string `json:"dir"`

	// Origin Origin's host and path, or empty.
	Origin string `json:"origin"`

	// Shown The directory written from your home.
	Shown string `json:"shown"`

	// State here is where the server works; repository is a repository's directory; directory is one in no repository; missing is not there.
	State FavoriteState `json:"state"`
}

// FavoriteState here is where the server works; repository is a repository's directory; directory is one in no repository; missing is not there.
type FavoriteState string

// FieldEntry The value given a field: option_id for an option field, option_ids for an option_list field, and text for a text, user or date field.
type FieldEntry struct {
	// ID The field's id.
	ID        string    `json:"id"`
	OptionID  *string   `json:"option_id,omitempty"`
	OptionIds *[]string `json:"option_ids,omitempty"`
	Text      *string   `json:"text,omitempty"`
}

// FieldOption One value a field allows.
type FieldOption struct {
	// ID Example: 1
	ID string `json:"id"`

	// Name Example: Fixed
	Name string `json:"name"`
}

// FileDiff A changed file's diff against HEAD.
type FileDiff struct {
	// Lines The diff, line by line, as git writes it — headers, hunks, and each line marked +, - or space — with terminal controls taken out; empty when git reports no difference.
	Lines []string `json:"lines"`

	// Path The file, as the working tree's changes list it.
	Path string `json:"path"`
}

// FollowUp One offer after opening: to link the pull request on the branch's issue (POST /api/issues/{key}/link), or to move that issue to the review status (POST /api/issues/{key}/transition). A move is offered only when Jira offers one that needs no fields.
type FollowUp struct {
	Action FollowUpAction `json:"action"`

	// IssueKey The Jira issue the checked-out branch names.
	//
	// Example: PROJ-412
	IssueKey string `json:"issue_key"`

	// Status Set only on a transition — the status the issue would move to.
	//
	// Example: In Review
	Status *string `json:"status,omitempty"`
}

// FollowUpAction defines model for FollowUp.Action.
type FollowUpAction string

// ForgeConfig defines model for ForgeConfig.
type ForgeConfig struct {
	Cli  *bool   `json:"cli,omitempty"`
	Host *string `json:"host,omitempty"`

	// Kind Empty for auto-detect, else github or gitlab.
	Kind *ForgeConfigKind `json:"kind,omitempty"`

	// Token Masked on read; empty or masked on write keeps the stored value.
	Token *string `json:"token,omitempty"`
}

// ForgeConfigKind Empty for auto-detect, else github or gitlab.
type ForgeConfigKind string

// GroupTag A user group an announcement offers to tag.
type GroupTag struct {
	// Checked Whether it starts checked — a team owning the changed paths links it, or it was chosen last time.
	Checked bool `json:"checked"`

	// FromOwners Whether it is offered because a team owning the changed paths is linked to it.
	FromOwners bool `json:"from_owners"`

	// Slack A Slack user or user group, by its ID and the name Slack shows for it.
	Slack SlackTarget `json:"slack"`
}

// Health defines model for Health.
type Health struct {
	// DryRun Whether writes are held back (the --dry-run flag).
	DryRun bool `json:"dry_run"`

	// ForgeNoun What the repository's forge calls a proposed change, lowercase — a "merge request" on GitLab and a "pull request" everywhere else — so the browser says what the terminal and the command line say.
	//
	// Example: merge request
	ForgeNoun string `json:"forge_noun"`

	// ForgeSigil The mark the forge writes before a proposed change's number: "!" on GitLab, "#" everywhere else.
	//
	// Example: !
	ForgeSigil string `json:"forge_sigil"`

	// Version The binary's version, or a short commit for a dev build.
	Version string `json:"version"`
}

// HookSetup The lefthook configuration offered for hooks lefthook does not manage.
type HookSetup struct {
	// Config The lefthook.yml that would run them; empty when nothing is offered.
	Config string `json:"config"`

	// Hooks The hooks found that lefthook does not manage.
	Hooks []UnmanagedHook `json:"hooks"`

	// Offered Whether there is anything to set up.
	Offered bool `json:"offered"`

	// Scripts How many hooks it keeps whole as scripts under .lefthook.
	Scripts int `json:"scripts"`
}

// HookSetupRequest defines model for HookSetupRequest.
type HookSetupRequest struct {
	// Verbatim Keep every hook whole as a script rather than turning plain commands into lefthook jobs.
	Verbatim *bool `json:"verbatim,omitempty"`
}

// HookSetupWritten defines model for HookSetupWritten.
type HookSetupWritten struct {
	// Scripts How many scripts were written under .lefthook beside lefthook.yml.
	Scripts int `json:"scripts"`
}

// Issue defines model for Issue.
type Issue struct {
	// Key Example: PROJ-412
	Key string `json:"key"`

	// Priority Absent when the issue has none.
	Priority *string `json:"priority,omitempty"`

	// Status The human status name, such as "In Progress".
	Status         string         `json:"status"`
	StatusCategory StatusCategory `json:"status_category"`
	Summary        string         `json:"summary"`

	// Tracker Where the issue lives: Jira, keyed like PROJ-412, or the repository's own forge, GitHub or GitLab, keyed by its number.
	Tracker IssueTracker `json:"tracker"`

	// Type The issue type name, such as Bug or Story.
	Type string `json:"type"`
}

// IssueDetail defines model for IssueDetail.
type IssueDetail struct {
	// Assignee Who the issue is assigned to; absent when no one is.
	Assignee *string `json:"assignee,omitempty"`

	// CommentTotal The total on the issue, which may exceed those returned.
	CommentTotal int `json:"comment_total"`

	// Comments Oldest first.
	Comments       []Comment      `json:"comments"`
	Description    string         `json:"description"`
	Key            string         `json:"key"`
	Priority       *string        `json:"priority,omitempty"`
	Reporter       string         `json:"reporter"`
	Status         string         `json:"status"`
	StatusCategory StatusCategory `json:"status_category"`
	Summary        string         `json:"summary"`

	// Tracker Where the issue lives: Jira, keyed like PROJ-412, or the repository's own forge, GitHub or GitLab, keyed by its number.
	Tracker IssueTracker `json:"tracker"`
	Type    string       `json:"type"`

	// URL The issue in the tracker's own web interface, for a link to open. Empty when the tracker's base URL cannot be read; never carries the base URL's username or password.
	URL string `json:"url"`
}

// IssueTracker Where the issue lives: Jira, keyed like PROJ-412, or the repository's own forge, GitHub or GitLab, keyed by its number.
type IssueTracker string

// IssuesConfig defines model for IssuesConfig.
type IssuesConfig struct {
	// Forge List the issues assigned to you on this repository's own forge, GitHub or GitLab, beside Jira's. Set per repository, over the home file's default.
	Forge *bool `json:"forge,omitempty"`
}

// IssuesPage defines model for IssuesPage.
type IssuesPage struct {
	Issues []Issue `json:"issues"`

	// StartAt The index of the first issue in this page.
	StartAt int `json:"start_at"`

	// Total How many issues the view matches in all.
	Total int `json:"total"`

	// Unavailable Each tracker a list drawing on Jira and the forge together could not read, so what is listed is not taken for all there is. Empty when every tracker answered.
	Unavailable []string `json:"unavailable"`
}

// JiraConfig defines model for JiraConfig.
type JiraConfig struct {
	BaseURL *string `json:"base_url,omitempty"`

	// Headers Extra request headers; values masked on read.
	Headers *map[string]string `json:"headers,omitempty"`

	// MarkdownComments Post comments written in Markdown as Jira's wiki markup.
	MarkdownComments *bool   `json:"markdown_comments,omitempty"`
	Project          *string `json:"project,omitempty"`

	// ReviewStatus The status an issue moves to once its pull request is open, e.g. "In Review". Empty makes no offer.
	ReviewStatus *string `json:"review_status,omitempty"`

	// Token Masked on read; empty or masked on write keeps the stored value.
	Token        *string     `json:"token,omitempty"`
	TokenCommand *string     `json:"token_command,omitempty"`
	TokenEnv     *string     `json:"token_env,omitempty"`
	User         *string     `json:"user,omitempty"`
	Views        *[]JiraView `json:"views,omitempty"`
}

// JiraView defines model for JiraView.
type JiraView struct {
	// Jql The query the view searches: a configured view's JQL narrowed to the issues assigned to you, unless it already names the assignee.
	Jql  string `json:"jql"`
	Name string `json:"name"`
}

// JobLog defines model for JobLog.
type JobLog struct {
	// Text The log's last lines, with every terminal control taken out.
	Text string `json:"text"`

	// Truncated Whether the log ran on before the lines kept.
	Truncated bool `json:"truncated"`
}

// KeyAction One action the terminal interface binds, as its help lists it.
type KeyAction struct {
	// Action The action's name, as ui.keys names it, e.g. comment.
	Action string `json:"action"`

	// Group The help group it is listed under, e.g. Issues.
	Group string `json:"group"`

	// Help The words the help says it in, e.g. change status.
	Help string `json:"help"`

	// Keys Every key that triggers it, in the terminal's names, e.g. c, C, ctrl+e.
	Keys []string `json:"keys"`

	// Shown The key the help shows, e.g. c, or 1-9 for the pane numbers.
	Shown string `json:"shown"`
}

// KeyList defines model for KeyList.
type KeyList struct {
	Actions []KeyAction `json:"actions"`

	// SingleKeyShortcuts Whether a single key pressed outside a text field acts (ui.web_shortcuts).
	SingleKeyShortcuts bool `json:"single_key_shortcuts"`
}

// LinkedIssue defines model for LinkedIssue.
type LinkedIssue struct {
	// Key The issue's key, a forge number without its
	Key string `json:"key"`

	// Origin Where the issue was found: the link the branch was given by hand, the branch's name, or the pull request's title or description.
	Origin LinkedIssueOrigin `json:"origin"`

	// Tracker Where the issue lives: Jira, keyed like PROJ-412, or the repository's own forge, GitHub or GitLab, keyed by its number.
	Tracker IssueTracker `json:"tracker"`

	// URL The issue's page, for a link to open; empty when the tracker gives none.
	URL string `json:"url"`
}

// LinkedIssueOrigin Where the issue was found: the link the branch was given by hand, the branch's name, or the pull request's title or description.
type LinkedIssueOrigin string

// LocalData The store's directory and the database files in it.
type LocalData struct {
	// Dir The directory the store keeps its files in.
	Dir string `json:"dir"`

	// DryRun Whether the server runs with --dry-run, which refuses a removal.
	DryRun *bool `json:"dry_run,omitempty"`

	// Files Each database file there, the cache first; a file not there is left out.
	Files []LocalDataFile `json:"files"`
}

// LocalDataFile One database file, with its companions counted in its size.
type LocalDataFile struct {
	// Bytes Its size with its -wal and -shm companions.
	Bytes int64 `json:"bytes"`

	// Holds How many of each thing it holds; empty when the file could not be read as a database.
	Holds []LocalDataHeld `json:"holds"`

	// Kind cache holds conveniences a session makes again; kept holds what the user decided, which removing all makes workflow ask again.
	Kind LocalDataFileKind `json:"kind"`

	// Name The file's name in the directory, as workflow.db or kept.db.
	Name string `json:"name"`
}

// LocalDataFileKind cache holds conveniences a session makes again; kept holds what the user decided, which removing all makes workflow ask again.
type LocalDataFileKind string

// LocalDataHeld defines model for LocalDataHeld.
type LocalDataHeld struct {
	Count int `json:"count"`

	// What What is counted, as scopes or repository groups.
	What string `json:"what"`
}

// LoggedWork Work just logged on an issue, as Jira recorded it.
type LoggedWork struct {
	// Key Example: PROJ-412
	Key string `json:"key"`

	// TimeSpent The duration as Jira recorded it.
	//
	// Example: 2h
	TimeSpent string `json:"time_spent"`
}

// MergeMethod How a pull request is merged — a merge commit, squashed, or rebased.
type MergeMethod string

// MergeOffer The pull request a merge would merge, and the methods its repository permits.
type MergeOffer struct {
	Methods []MergeMethod `json:"methods"`
	Pull    PullRequest   `json:"pull"`
}

// MergeRequest defines model for MergeRequest.
type MergeRequest struct {
	// Method How a pull request is merged — a merge commit, squashed, or rebased.
	Method MergeMethod `json:"method"`
}

// MessagingConfig defines model for MessagingConfig.
type MessagingConfig struct {
	// AccessToken The user token's current access token (xoxe.xoxp-…), when this file keeps it. workflow replaces it on every refresh. Masked on read; empty or masked on write keeps the stored value.
	AccessToken  *string   `json:"access_token,omitempty"`
	Announcement *string   `json:"announcement,omitempty"`
	Channel      *string   `json:"channel,omitempty"`
	Channels     *[]string `json:"channels,omitempty"`

	// ClientID The Slack app's client ID, which its rotating user token is refreshed with. Slack only; set together with webhook_url it is refused. Not a secret.
	ClientID *string `json:"client_id,omitempty"`

	// ClientSecret The Slack app's client secret, when this file keeps the user token's credentials rather than the macOS keychain. Masked on read; empty or masked on write keeps the stored value.
	ClientSecret *string `json:"client_secret,omitempty"`

	// ExpiresAt When the access token expires, RFC 3339 UTC; written by workflow.
	ExpiresAt *string `json:"expires_at,omitempty"`

	// Kind The service posts go to. Empty is read as slack. It decides the message body and link markup the notifier sends.
	Kind *MessagingConfigKind `json:"kind,omitempty"`

	// RefreshToken The user token's current refresh token (xoxe-1-…), when this file keeps it. workflow replaces it on every refresh. Masked on read; empty or masked on write keeps the stored value.
	RefreshToken *string `json:"refresh_token,omitempty"`

	// WebhookURL A credential; masked on read, preserved on write like a token.
	WebhookURL *string `json:"webhook_url,omitempty"`
}

// MessagingConfigKind The service posts go to. Empty is read as slack. It decides the message body and link markup the notifier sends.
type MessagingConfigKind string

// MessagingDestination defines model for MessagingDestination.
type MessagingDestination struct {
	// Author Who a post would come from; empty if not resolved.
	Author string `json:"author"`

	// Channel The default channel; empty when a webhook carries its own.
	Channel string `json:"channel"`

	// Channels The default first, then the alternates.
	Channels []string `json:"channels"`

	// Configured Whether a transport is set up to post — a user token or a webhook. A webhook service has no channel, so channel presence cannot stand in for this.
	Configured bool `json:"configured"`

	// Service The service posts go to — Slack, Teams, Discord or webhook.
	Service string `json:"service"`
}

// MovedIssue An issue that was just moved, and the status it is now in.
type MovedIssue struct {
	// Key Example: PROJ-412
	Key string `json:"key"`

	// Status Example: In Review
	Status string `json:"status"`
}

// OpenPullRequestRequest The pull request to open for the checked-out branch.
type OpenPullRequestRequest struct {
	// Assignees Usernames to assign the pull request to.
	Assignees *[]string `json:"assignees,omitempty"`

	// Base The branch to merge into.
	//
	// Example: main
	Base string `json:"base"`

	// Body The pull request body; may be empty.
	Body *string `json:"body,omitempty"`

	// Draft Whether to open it as a draft.
	Draft *bool `json:"draft,omitempty"`

	// Labels Label names to add to the pull request.
	Labels *[]string `json:"labels,omitempty"`

	// Reviewers Usernames to request a review from. A name holding a slash is a team, org/team, requested as a team on GitHub; on GitLab a group/subgroup stands for its direct members.
	Reviewers *[]string `json:"reviewers,omitempty"`

	// Title The pull request title.
	//
	// Example: fix: redact tokens before they reach the request log
	Title string `json:"title"`
}

// OpenedPullRequest A pull request that was just opened, with a warning when it opened but its reviewers, assignees or labels could not all be added, and what can be offered next.
type OpenedPullRequest struct {
	// FollowUps What the browser can offer now that the pull request is open, in the order the terminal offers them — the link, then the move. Empty when the branch names no Jira issue, or neither applies.
	FollowUps []FollowUp  `json:"follow_ups"`
	Pull      PullRequest `json:"pull"`

	// Warning Set only when the pull opened but adding its reviewers, assignees or labels did not fully succeed, so a partial success is not reported as a failure.
	Warning *string `json:"warning,omitempty"`
}

// OwnerName A forge owner as CODEOWNERS names it, without its @ — a user, or org/team.
//
// Example: acme/control-plane
type OwnerName = string

// OwnerTag A code owner and what is known of them on Slack: linked (to a user, or a team to a user group), decided not on Slack, or not asked yet.
type OwnerTag struct {
	Kind OwnerTagKind `json:"kind"`

	// Owner A forge owner as CODEOWNERS names it, without its @ — a user, or org/team.
	//
	// Example: acme/control-plane
	Owner OwnerName `json:"owner"`

	// Slack A Slack user or user group, by its ID and the name Slack shows for it.
	Slack *SlackTarget  `json:"slack,omitempty"`
	State OwnerTagState `json:"state"`
}

// OwnerTagKind defines model for OwnerTag.Kind.
type OwnerTagKind string

// OwnerTagState defines model for OwnerTag.State.
type OwnerTagState string

// PanelProblems Why each panel whose read failed was not read, so a failed read is shown as a failure rather than as the panel's empty state; absent when every panel read. A failed panel still carries its empty answer — or, for the review, the answer the forge last gave for the branch at its head — beside its problem. A service that is not set up — no credential, no forge the origin names — carries a problem whose code is not_set_up, with how to set it up, to be shown as guidance rather than as a failure; no repository is no problem. Each detail is the curated one an error answer carries, never a host, a path or a credential.
type PanelProblems struct {
	// Branch Why the checked-out branch could not be read.
	Branch *Problem `json:"branch,omitempty"`

	// Changes Why the working tree's changes could not be read.
	Changes *Problem `json:"changes,omitempty"`

	// Issues Why the view's first page could not be read.
	Issues *Problem `json:"issues,omitempty"`

	// Review Why the branch's pull request could not be read: the forge's refusal, or the branch's when the branch could not be read.
	Review *Problem `json:"review,omitempty"`
}

// People Every code owner decided on this forge host, then the branch's undecided owners.
type People struct {
	Owners []OwnerTag `json:"owners"`
}

// PersonLink Whom a code owner is on Slack: slack_id, or not_on_slack true — one or the other.
type PersonLink struct {
	// Channel The channel whose members a user was picked from, so the label is read from there; the configured channel when left out.
	Channel *string `json:"channel,omitempty"`

	// NotOnSlack Mark the owner not on Slack, so they are not asked again.
	NotOnSlack bool `json:"not_on_slack"`

	// Owner A forge owner as CODEOWNERS names it, without its @ — a user, or org/team.
	//
	// Example: acme/control-plane
	Owner OwnerName `json:"owner"`

	// SlackID A user ID for a user owner, a user group ID for a team.
	SlackID *string `json:"slack_id,omitempty"`
}

// Place A directory the server works in, as it is now. Each path is also written from your home, as ~/src/api, for showing.
type Place struct {
	// Config The configuration files that apply, each written from your home, the repository's first; empty when the defaults apply.
	Config []string `json:"config"`

	// Dir The directory, as an absolute path.
	Dir string `json:"dir"`

	// Origin Origin's host and path, as github.com/acme/api, or empty when there is none.
	Origin string `json:"origin"`

	// Root The repository's root, or empty outside a repository.
	Root string `json:"root"`

	// RootShown The root written from your home, or empty.
	RootShown string `json:"root_shown"`

	// Shown The directory written from your home.
	Shown string `json:"shown"`

	// Within The path from the root to the directory, or empty at the root or outside a repository.
	Within string `json:"within"`
}

// PostLength How long the summary's text is once rendered for the messaging service set up, as that service measures it, against the most it takes. Left out where no messaging is set up, or where the service names no limit (a plain webhook). A post longer than the limit is refused with too_long, and nothing is sent.
type PostLength struct {
	// Count The text's length, rendered for the service.
	Count int `json:"count"`

	// Limit The most the service takes.
	Limit int `json:"limit"`

	// Service The service the summary would be posted to, such as Discord.
	Service string `json:"service"`

	// Unit What count and limit are counted in: characters, or bytes of the whole payload for Teams, whose limit is put that way.
	Unit PostLengthUnit `json:"unit"`
}

// PostLengthUnit What count and limit are counted in: characters, or bytes of the whole payload for Teams, whose limit is put that way.
type PostLengthUnit string

// Problem An RFC 9457 problem details object. The detail is safe to show and never carries a secret; code is a stable, machine-readable reason.
type Problem struct {
	// Code A stable, machine-readable reason. not_set_up is a service with nothing set up to ask — no credential, no forge the origin names, no Taskwarrior installed, no git user.email — whose detail says how to set it up; unprocessable is a request or a setting that cannot be used as it is.
	Code ProblemCode `json:"code"`

	// Detail A human-readable explanation specific to this occurrence.
	Detail string `json:"detail"`

	// Status The HTTP status code.
	Status int `json:"status"`

	// Title A short, human-readable summary of the problem type.
	Title string `json:"title"`

	// Type A URI that identifies the problem type.
	//
	// Example: https://jacob-delgado.github.io/workflow/docs/errors/#not-found
	Type string `json:"type"`
}

// ProblemCode A stable, machine-readable reason. not_set_up is a service with nothing set up to ask — no credential, no forge the origin names, no Taskwarrior installed, no git user.email — whose detail says how to set it up; unprocessable is a request or a setting that cannot be used as it is.
type ProblemCode string

// PullRequest defines model for PullRequest.
type PullRequest struct {
	Approvals        int                  `json:"approvals"`
	ChangesRequested bool                 `json:"changes_requested"`
	Draft            bool                 `json:"draft"`
	Mergeable        PullRequestMergeable `json:"mergeable"`

	// Number The GitHub number or GitLab IID.
	Number int `json:"number"`

	// State Whether it is still open, has merged, or was closed without merging. The branch's pull request is found open or merged; a merged one has no CI to report.
	State PullRequestState `json:"state"`
	Title string           `json:"title"`
	URL   string           `json:"url"`
}

// PullRequestMergeable defines model for PullRequest.Mergeable.
type PullRequestMergeable string

// PullRequestState Whether it is still open, has merged, or was closed without merging. The branch's pull request is found open or merged; a merged one has no CI to report.
type PullRequestState string

// PullRequestConfig defines model for PullRequestConfig.
type PullRequestConfig struct {
	// TitleSource Where a pull request's title comes from: "commit" (the default) takes the branch's oldest commit, "issue" takes the issue it names.
	TitleSource *string `json:"title_source,omitempty"`
}

// PullRequestDraft A pull request composed for the branch, editable before opening.
type PullRequestDraft struct {
	// Base The branch it would merge into.
	Base string `json:"base"`

	// Body The proposed body, from the template, commits, and issue.
	Body string `json:"body"`

	// Draft Whether it would open as a draft; always false in a fresh draft.
	Draft bool `json:"draft"`

	// Head The branch with the work; the open always uses the checked-out one.
	Head string `json:"head"`

	// NeedsPush Whether the branch must be pushed first; the open pushes it.
	NeedsPush bool `json:"needs_push"`

	// Reviewers The proposed reviewers: the code owners of the paths the branch changes, as CODEOWNERS on the base names them, without the author. People come first, then teams as org/team (a GitLab group as group/subgroup). Empty when no CODEOWNERS covers the changes or it cannot be read.
	//
	// Example: ["ana","acme/control-plane"]
	Reviewers []string `json:"reviewers"`

	// Template The template the body starts from, by name; empty when there is none.
	Template string `json:"template"`

	// Templates The repository's pull request templates by name, in the order the terminal's ctrl+t cycles them; empty when it has none.
	Templates []string `json:"templates"`

	// Title The proposed title, from the first commit or the issue.
	Title string `json:"title"`
}

// PullRequestText A pull request's title and description.
type PullRequestText struct {
	Body  string `json:"body"`
	Title string `json:"title"`
}

// QueuedAnnouncement An announcement held until a pull request's CI passes, and how it stands: waiting for the CI, being posted, posted, or dropped unposted with the reason.
type QueuedAnnouncement struct {
	// Channel The channel it posts to, or empty for a webhook's own channel.
	Channel string `json:"channel"`

	// Pull The number of the pull request whose CI it waits on.
	Pull int `json:"pull"`

	// Reason Why a dropped announcement was not posted: the CI failed, the branch's pull request is another one, or the post failed.
	Reason *string                 `json:"reason,omitempty"`
	State  QueuedAnnouncementState `json:"state"`
}

// QueuedAnnouncementState defines model for QueuedAnnouncement.State.
type QueuedAnnouncementState string

// RepoGroups The Slack user groups a repository's announcements may tag.
type RepoGroups struct {
	Groups []SlackTarget `json:"groups"`

	// Repository The repository's name, as its forge path or its directory.
	//
	// Example: acme/widgets
	Repository string `json:"repository"`
}

// RepoGroupsRequest The user groups, by ID, this repository may tag from now on.
type RepoGroupsRequest struct {
	Ids []string `json:"ids"`
}

// Repositories Where the server works, the repository's worktrees, and your favorite directories.
type Repositories struct {
	// Favorites Your favorites, by path.
	Favorites []Favorite `json:"favorites"`

	// FavoritesKept Whether a favorite can be marked or forgotten here: false when the store keeps nothing, or under --dry-run.
	FavoritesKept bool `json:"favorites_kept"`

	// Here A directory the server works in, as it is now. Each path is also written from your home, as ~/src/api, for showing.
	Here Place `json:"here"`

	// Worktrees The working trees of the repository the server works in, the main one first, as git lists them; empty outside a repository.
	Worktrees []Worktree `json:"worktrees"`

	// WorktreesError Why the worktrees could not be read, in words that never name a path or a host; empty when they were.
	WorktreesError string `json:"worktrees_error"`
}

// Rerun defines model for Rerun.
type Rerun struct {
	// Reran Whether the forge re-ran anything; false when the failure had no job to restart.
	Reran bool `json:"reran"`
}

// Review defines model for Review.
type Review struct {
	// Announced Whether the pull request was already announced at the moment it is at now — ready for review, its CI red, merged — from the browser, the terminal or workflow announce, as the store remembers. The store is read at most once every timing.ci_interval, and never under --dry-run, when this is always false.
	Announced bool `json:"announced"`

	// Ci The pull request's CI; absent when none is found, the pull request is not open, or its CI cannot be read — unless the event stream holds the CI last read for the same pull request at the same head.
	Ci *CI `json:"ci,omitempty"`

	// CiError Why the open pull request's CI could not be read; absent when it was, or was not asked about. The detail is curated, never a host or a credential.
	CiError *Problem `json:"ci_error,omitempty"`

	// Found Whether a pull request was found for the branch.
	Found bool `json:"found"`

	// Issue The issue the branch and its pull request are for; absent when none is named.
	Issue *LinkedIssue `json:"issue,omitempty"`

	// Pull The branch's pull request; absent when none is found.
	Pull *PullRequest `json:"pull,omitempty"`
}

// ReviewQueue defines model for ReviewQueue.
type ReviewQueue struct {
	// Available Whether there is a forge to ask. False outside a repository, and when origin is on no forge workflow can read — not GitHub or GitLab, or a self-hosted one forge.kind and forge.host do not name — and requests is then empty.
	Available bool `json:"available"`

	// Requests The open pull or merge requests that ask for your review, the longest-waiting first. Empty when none does, or when there is no forge to ask.
	Requests []ReviewRequest `json:"requests"`
}

// ReviewRequest defines model for ReviewRequest.
type ReviewRequest struct {
	// Author Who opened it, and so who asks for the review.
	Author string  `json:"author"`
	Ci     CIState `json:"ci"`
	Draft  bool    `json:"draft"`

	// Number The GitHub number or GitLab IID.
	Number int `json:"number"`

	// OpenedAt RFC 3339; when it was opened, which is how long it has waited — the zero time if the forge did not give one.
	OpenedAt time.Time `json:"opened_at"`

	// Repository The owner/name (GitHub) or group/project (GitLab) it is in, since the queue spans repositories; empty when the forge did not say.
	//
	// Example: jacob-delgado/workflow
	Repository string `json:"repository"`
	Title      string `json:"title"`
	URL        string `json:"url"`
}

// Run A git run and how it stands: running, or how it ended, with what it wrote.
type Run struct {
	// Kind A git run: the pre-commit hook on what is staged, a rebase onto the base, an amend of the last commit, or a fixup! of an earlier one.
	Kind RunKind `json:"kind"`

	// Lines What the program wrote, standard output and standard error in the order written, with terminal controls taken out. A run the event stream carries holds its last 200 lines.
	Lines []string `json:"lines"`

	// Outcome What the run did, once it has ended — Rebased onto main, the pre-commit hook failed — and empty while it runs.
	Outcome string `json:"outcome"`

	// State How the run stands: in progress, succeeded, refused — the program ended with a failure, a hook that failed or a rebase stopped at a conflict — or stopped by DELETE /api/runs/current.
	State RunState `json:"state"`

	// Title What is running, as the terminal titles it, such as git rebase.
	Title string `json:"title"`
}

// RunState How the run stands: in progress, succeeded, refused — the program ended with a failure, a hook that failed or a rebase stopped at a conflict — or stopped by DELETE /api/runs/current.
type RunState string

// RunEvent One line of a run's stream: the run itself, as it starts and as it ends, or one line of its output.
type RunEvent struct {
	// Line A line the program wrote, with terminal controls taken out.
	Line *string `json:"line,omitempty"`

	// Run A git run and how it stands: running, or how it ended, with what it wrote.
	Run *Run `json:"run,omitempty"`
}

// RunKind A git run: the pre-commit hook on what is staged, a rebase onto the base, an amend of the last commit, or a fixup! of an earlier one.
type RunKind string

// RunRequest Which run to start, and for a fixup the commit it fixes up.
type RunRequest struct {
	// Commit For fixup, the hash of the commit to record a fixup! of, as the branch lists it; it must be one not yet pushed. Ignored otherwise.
	Commit *string `json:"commit,omitempty"`

	// Kind A git run: the pre-commit hook on what is staged, a rebase onto the base, an amend of the last commit, or a fixup! of an earlier one.
	Kind RunKind `json:"kind"`
}

// SetupOffer The first-run setup offered where the server works.
type SetupOffer struct {
	// Keychain The OS keychain can keep the Jira token out of the file.
	Keychain bool `json:"keychain"`

	// Needed No configuration file applies where the server works, so one can be set up.
	Needed bool `json:"needed"`

	// Places Where the file may go, the repository first.
	Places []SetupPlace `json:"places"`
}

// SetupPlace defines model for SetupPlace.
type SetupPlace struct {
	// Path The file it would be, as an absolute path.
	Path string `json:"path"`

	// Place repository is the repository's root, or the working directory outside a repository; home is the home directory.
	Place SetupPlaceName `json:"place"`

	// Shown The file written from your home.
	Shown string `json:"shown"`
}

// SetupPlaceName repository is the repository's root, or the working directory outside a repository; home is the home directory.
type SetupPlaceName string

// SetupRequest defines model for SetupRequest.
type SetupRequest struct {
	// JiraBaseURL Jira's address; empty leaves Jira out, and the forge's issues are the tracker.
	JiraBaseURL string `json:"jira_base_url"`

	// JiraToken The Jira personal access token. Never echoed back.
	JiraToken string `json:"jira_token"`

	// KeepUnchecked Write Jira's address and token even when Jira does not accept them, or cannot be asked. An address that is no http or https address, or that carries a username and password, is never kept.
	KeepUnchecked bool `json:"keep_unchecked"`

	// Keychain Keep the Jira token in the OS keychain rather than in the file.
	Keychain bool `json:"keychain"`

	// Place repository is the repository's root, or the working directory outside a repository; home is the home directory.
	Place SetupPlaceName `json:"place"`

	// WebhookURL A Slack incoming webhook, saved unchecked; empty posts with the Slack user token.
	WebhookURL string `json:"webhook_url"`
}

// SetupResult defines model for SetupResult.
type SetupResult struct {
	// JiraUser Whom the token authenticates as; empty when Jira was left out or kept unchecked.
	JiraUser string `json:"jira_user"`

	// Keychain The OS keychain keeps the token, and the file the command that reads it back.
	Keychain bool `json:"keychain"`

	// NotIgnored The file is in a repository that does not ignore it, so it could be committed.
	NotIgnored bool `json:"not_ignored"`

	// Path The file written, as an absolute path.
	Path string `json:"path"`

	// Reopened The server works with the file now. False when it could not take it up, which a restart of workflow --web does.
	Reopened bool `json:"reopened"`

	// Shown The file written from your home.
	Shown string `json:"shown"`
}

// SlackDirectory People or user groups read from Slack, or the scope the token lacks to read them.
type SlackDirectory struct {
	Entries []SlackTarget `json:"entries"`

	// MissingScope The scope to add to the Slack token for this read; entries are empty then.
	//
	// Example: users:read
	MissingScope *string `json:"missing_scope,omitempty"`
}

// SlackTarget A Slack user or user group, by its ID and the name Slack shows for it.
type SlackTarget struct {
	// ID A user ID (U or W…) or a user group ID (S…).
	//
	// Example: U024BE7LH
	ID string `json:"id"`

	// Label The name to show for it.
	Label string `json:"label"`
}

// Snapshot The full read state carried by one event-stream message: everything the cockpit shows, together.
type Snapshot struct {
	Branch Branch `json:"branch"`

	// Branches The branches named for one of your issues, local ones and those only the remote has — the record of what is in flight. The detail panels (branch, changes, review) describe the checked-out branch alone; this lists every issue of yours that has a branch, so the issues list can mark them all in flight, not the one on HEAD. An issue is yours when the tracker says it is assigned to you and not done; with no tracker to ask, every branch that names an issue is listed.
	Branches []TaskBranch `json:"branches"`
	Changes  ChangeList   `json:"changes"`

	// CommitTypes The commit types a new commit may take, in the order to offer them — the terminal composer's list: commit.types, trimmed, when the configuration names any, else the built-in Conventional Commit types. A commit whose type is not among them is refused.
	//
	// Example: ["feat","fix","docs"]
	CommitTypes []string `json:"commit_types"`

	// Here The directory the server works in, as an absolute path, so a page notices a switch made elsewhere and reads again.
	Here string `json:"here"`

	// HooksUnmanaged How many git hooks the repository's hooks directory holds that lefthook does not manage, while the repository configures no lefthook — which GET /api/hooks/setup offers to set up; 0 otherwise.
	HooksUnmanaged int                  `json:"hooks_unmanaged"`
	Issues         IssuesPage           `json:"issues"`
	Messaging      MessagingDestination `json:"messaging"`

	// Problems Why each panel whose read failed was not read, so a failed read is shown as a failure rather than as the panel's empty state; absent when every panel read. A failed panel still carries its empty answer — or, for the review, the answer the forge last gave for the branch at its head — beside its problem. A service that is not set up — no credential, no forge the origin names — carries a problem whose code is not_set_up, with how to set it up, to be shown as guidance rather than as a failure; no repository is no problem. Each detail is the curated one an error answer carries, never a host, a path or a credential.
	Problems *PanelProblems `json:"problems,omitempty"`

	// QueuedAnnouncement An announcement held until a pull request's CI passes, and how it stands: waiting for the CI, being posted, posted, or dropped unposted with the reason.
	QueuedAnnouncement *QueuedAnnouncement `json:"queued_announcement,omitempty"`
	Review             Review              `json:"review"`

	// Run The git run going now (POST /api/runs), with its last 200 lines, so a page opened while it runs sees it; absent when none is going.
	Run *Run `json:"run,omitempty"`

	// SuggestedScope The scope a new commit opens on — the terminal composer's rule: the scope last committed with in this repository, else commit.default_scope, else empty. The server reads the learned one from its store once, and once more after a commit here records one, not on every message, and never under --dry-run, when the default alone applies.
	//
	// Example: api
	SuggestedScope string `json:"suggested_scope"`

	// Tasks What the event stream carries of your Taskwarrior tasks: the started one, as active — absent when none is started — and every task linked to an issue. Until Taskwarrior has answered both reads the summary makes, it is not available, with no active task and no linked one.
	Tasks TasksSummary `json:"tasks"`
}

// StagingRequest What to stage or unstage: one changed file, or all of them — one or the other, never both.
type StagingRequest struct {
	// All Every change: for staging, each one the index does not hold yet; for unstaging, each staged one.
	All *bool `json:"all,omitempty"`

	// Path A changed file, by the path the working tree's changes list it under (a rename's new path).
	//
	// Example: internal/config/config.go
	Path *string `json:"path,omitempty"`
}

// StatusCategory defines model for StatusCategory.
type StatusCategory string

// StatusChange A status change the tracker offers an issue, and the fields it cannot be made without.
type StatusChange struct {
	// Fields The fields the tracker refuses the change without, ordered by name.
	Fields []StatusChangeField `json:"fields"`

	// ID The change's id, which applying it names.
	//
	// Example: 5
	ID string `json:"id"`

	// Name The change's own name, which can differ from where it leads.
	//
	// Example: Resolve Issue
	Name string `json:"name"`

	// ToStatus Example: Resolved
	ToStatus         string         `json:"to_status"`
	ToStatusCategory StatusCategory `json:"to_status_category"`
}

// StatusChangeField A field a status change needs, and how it is filled.
type StatusChangeField struct {
	// ID Example: resolution
	ID string `json:"id"`

	// Kind How the field is filled: one of its options, any number of them, free text, a username, a date as 2026-09-21, or only_jira for one only Jira's own screen can fill, such as a cascading select, which keeps the change out of reach here.
	Kind StatusChangeFieldKind `json:"kind"`

	// Name Example: Resolution
	Name string `json:"name"`

	// Options The values an option or option_list field allows; empty for the others.
	Options []FieldOption `json:"options"`
}

// StatusChangeFieldKind How the field is filled: one of its options, any number of them, free text, a username, a date as 2026-09-21, or only_jira for one only Jira's own screen can fill, such as a cascading select, which keeps the change out of reach here.
type StatusChangeFieldKind string

// StatusChangeRequest The status change to make, and a value for each field it needs.
type StatusChangeRequest struct {
	// Fields A value for each field the change needs, and no other.
	Fields []FieldEntry `json:"fields"`

	// TransitionID The change's id, as GET /api/issues/{key}/transitions lists it.
	TransitionID string `json:"transition_id"`
}

// StoreConfig defines model for StoreConfig.
type StoreConfig struct {
	// Disabled Turn off the on-disk store, keeping nothing between sessions. Off by default: the store is on and never holds a secret.
	Disabled *bool `json:"disabled,omitempty"`
}

// Task One task as Taskwarrior holds it. A date the task does not have is absent, never the zero time.
type Task struct {
	// Annotations The notes on the task, oldest first.
	Annotations []TaskAnnotation `json:"annotations"`
	Description string           `json:"description"`
	Due         *time.Time       `json:"due,omitempty"`

	// End When the task was completed or deleted.
	End *time.Time `json:"end,omitempty"`

	// Entry When the task was created.
	Entry time.Time `json:"entry"`

	// ID The working-set number; 0 for a task not in the working set.
	ID int `json:"id"`

	// IssueKey The issue the task is linked to, from its jiraid attribute; empty when it tracks none.
	//
	// Example: PROJ-412
	IssueKey string `json:"issue_key"`

	// IssueURL The issue's page: the tracker's, for a task naming an issue where the tracker builds issue pages (Jira); otherwise (the forge's issues as the tracker, or a task naming no issue) the task's jiraurl attribute when it is an http or https address; empty otherwise.
	IssueURL string `json:"issue_url"`

	// Modified When the task last changed.
	Modified time.Time `json:"modified"`

	// Priority H, M, L or empty.
	Priority string `json:"priority"`

	// Project Empty when the task has none.
	Project   string     `json:"project"`
	Scheduled *time.Time `json:"scheduled,omitempty"`

	// Start When the task was started; present only while it is.
	Start  *time.Time `json:"start,omitempty"`
	Status TaskStatus `json:"status"`
	Tags   []string   `json:"tags"`

	// Until When Taskwarrior deletes the task.
	Until *time.Time `json:"until,omitempty"`

	// Urgency Taskwarrior's own urgency; the list is ordered by it.
	Urgency float64 `json:"urgency"`

	// UUID Example: 5f3c9a1e-8b2d-4c6f-9e7a-1d2b3c4d5e6f
	UUID string `json:"uuid"`

	// Wait Until when the task is hidden from the list's usual reports.
	Wait *time.Time `json:"wait,omitempty"`
}

// TaskStatus defines model for Task.Status.
type TaskStatus string

// TaskAnnotation A note on a task, and when it was written.
type TaskAnnotation struct {
	Description string    `json:"description"`
	Entry       time.Time `json:"entry"`
}

// TaskBranch A branch named for an issue, by the branch-name convention: a local one, or one only the remote has, which checking out creates here.
type TaskBranch struct {
	// Current Whether this is the checked-out branch.
	Current bool `json:"current"`

	// IssueKey The issue the branch is named for — a Jira key or a forge issue number, per the branch-name convention.
	//
	// Example: PROJ-412
	IssueKey string `json:"issue_key"`

	// Name The local branch name.
	//
	// Example: fix/PROJ-412-redact-tokens
	Name string `json:"name"`

	// Remote Whether only the remote has the branch.
	Remote *bool `json:"remote,omitempty"`

	// Worktree The directory of another worktree of the repository that has the branch checked out, as an absolute path; empty when none does. git will not check such a branch out here, so it is switched to there instead.
	Worktree *string `json:"worktree,omitempty"`

	// WorktreeMissing Whether that worktree's directory is gone: git holds the branch for it until it is pruned, so it can be neither checked out nor switched to.
	WorktreeMissing *bool `json:"worktree_missing,omitempty"`

	// WorktreeShown That worktree's directory written from your home; empty when none.
	WorktreeShown *string `json:"worktree_shown,omitempty"`
}

// TaskLine A line in Taskwarrior's own grammar: words, with attributes such as project:web, due:friday or +tag among them.
type TaskLine struct {
	// Line The line, as it would follow `task add` or `task <id> modify`.
	//
	// Example: Write the release notes project:workflow due:friday
	Line string `json:"line"`
}

// TaskList Your pending Taskwarrior tasks, and what the server knows of the Taskwarrior that answered.
type TaskList struct {
	// Added The uuid of the task the write this list answers added — an add or a track — so the page can name it even when the active context leaves it out of tasks. Absent after any other write, and on a read.
	Added *string `json:"added,omitempty"`

	// Available Whether there is a Taskwarrior to ask: false when it is turned off by taskwarrior.disabled, not installed, not Taskwarrior (go-task is also called task), too old, never run, or its taskrc has a malformed line.
	Available bool `json:"available"`

	// Context The name of Taskwarrior's active context, whose filter the list applies; empty for none.
	Context string `json:"context"`

	// Reason Why Taskwarrior is not available, safe to show; empty when it is.
	Reason string `json:"reason"`

	// ReasonCode Why Taskwarrior is not available, as a code the page can act on without reading reason: not installed, a task program that is not Taskwarrior (go-task, most likely), too old, never run, turned off by taskwarrior.disabled, a taskrc with a malformed line, or unavailable for a reason workflow doctor explains, or taskwarrior settings saved since workflow started, which apply once it restarts. Absent when Taskwarrior is available.
	ReasonCode *TaskListReasonCode `json:"reason_code,omitempty"`

	// Said What the write this list answers has to add: how many operations an undo reverted, what a sync printed, or that a tracked issue's task was created but not annotated. Empty otherwise.
	Said string `json:"said"`

	// SyncAvailable Whether the taskrc names a sync backend, so a sync has somewhere to go.
	SyncAvailable bool `json:"sync_available"`

	// Tasks The pending tasks of the active context, most urgent first, waiting ones included. Empty when Taskwarrior is not available.
	Tasks []Task `json:"tasks"`
}

// TaskListReasonCode Why Taskwarrior is not available, as a code the page can act on without reading reason: not installed, a task program that is not Taskwarrior (go-task, most likely), too old, never run, turned off by taskwarrior.disabled, a taskrc with a malformed line, or unavailable for a reason workflow doctor explains, or taskwarrior settings saved since workflow started, which apply once it restarts. Absent when Taskwarrior is available.
type TaskListReasonCode string

// TaskText The text of a note on a task.
type TaskText struct {
	// Text The note; every word stays a word, never an attribute.
	//
	// Example: Waiting on the forge's rate limit to reset
	Text string `json:"text"`
}

// TasksSummary What the event stream carries of your Taskwarrior tasks: the started one, as active — absent when none is started — and every task linked to an issue. Until Taskwarrior has answered both reads the summary makes, it is not available, with no active task and no linked one.
type TasksSummary struct {
	// Active One task as Taskwarrior holds it. A date the task does not have is absent, never the zero time.
	Active *Task `json:"active,omitempty"`

	// Available Whether Taskwarrior answered: false when there is none to ask, as in TaskList, and when it was found but could not be read.
	Available bool `json:"available"`

	// Linked Every task linked to an issue, whatever its status but deleted, and whatever context hides it. Empty unless available.
	Linked []Task `json:"linked"`

	// Reason Why Taskwarrior is not available, safe to show; empty when it is.
	Reason string `json:"reason"`
}

// TaskwarriorConfig defines model for TaskwarriorConfig.
type TaskwarriorConfig struct {
	// Disabled Turn off the Taskwarrior integration even where Taskwarrior is installed.
	Disabled *bool `json:"disabled,omitempty"`

	// Program The task program to run: a name looked up on PATH, or a path. Empty tries every task in an absolute PATH directory and keeps the first that is Taskwarrior 3.5.0 or newer.
	Program *string `json:"program,omitempty"`
}

// TimingConfig defines model for TimingConfig.
type TimingConfig struct {
	// CiInterval A Go duration; empty for the default.
	CiInterval *string `json:"ci_interval,omitempty"`

	// RequestTimeout A Go duration such as 20s; empty for the default.
	RequestTimeout *string `json:"request_timeout,omitempty"`
}

// TrackIssueRequest The issue to track in Taskwarrior.
type TrackIssueRequest struct {
	// IssueKey The issue the task is for.
	//
	// Example: PROJ-412
	IssueKey string `json:"issue_key"`
}

// UIConfig defines model for UIConfig.
type UIConfig struct {
	ASCII *bool `json:"ascii,omitempty"`

	// Color Empty for auto, or "never".
	Color *UIConfigColor `json:"color,omitempty"`

	// CommentsShown How many comments the detail shows; 0 means the built-in default.
	CommentsShown *int `json:"comments_shown,omitempty"`

	// Keys Map from a key action to the key that triggers it; see the configuration docs for the actions.
	Keys   *map[string]string `json:"keys,omitempty"`
	Mouse  *bool              `json:"mouse,omitempty"`
	Notify *bool              `json:"notify,omitempty"`

	// WebShortcuts Whether the web page's single-key shortcuts are on. Off unless set; ? and the command palette work either way.
	WebShortcuts *bool `json:"web_shortcuts,omitempty"`
}

// UIConfigColor Empty for auto, or "never".
type UIConfigColor string

// UnmanagedHook defines model for UnmanagedHook.
type UnmanagedHook struct {
	// Lines How many lines its script holds.
	Lines int `json:"lines"`

	// Name Example: pre-commit
	Name string `json:"name"`
}

// ViewList defines model for ViewList.
type ViewList struct {
	Views []JiraView `json:"views"`
}

// WorklogRequest Time spent on a Jira issue, and an optional note.
type WorklogRequest struct {
	// Comment A note on the work; left out, the worklog carries none.
	Comment *string `json:"comment,omitempty"`

	// TimeSpent The duration in Jira's words, such as 2h, 30m or 1d 4h.
	TimeSpent string `json:"time_spent"`
}

// Worktree One working tree of the repository the server works in.
type Worktree struct {
	// Branch The branch it has checked out, or empty when its HEAD is detached.
	Branch string `json:"branch"`

	// Dir The worktree's directory, as an absolute path.
	Dir string `json:"dir"`

	// Head The commit it has checked out, abbreviated.
	Head string `json:"head"`

	// Locked Whether git keeps it from being removed or pruned.
	Locked bool `json:"locked"`

	// Shown The directory written from your home.
	Shown string `json:"shown"`

	// State here is the worktree the server works in; worktree is another; missing is one git still lists whose directory is gone.
	State WorktreeState `json:"state"`
}

// WorktreeState here is the worktree the server works in; worktree is another; missing is one git still lists whose directory is gone.
type WorktreeState string

// TaskUUID Example: 5f3c9a1e-8b2d-4c6f-9e7a-1d2b3c4d5e6f
type TaskUUID = string

// GetActivityParams defines parameters for GetActivity.
type GetActivityParams struct {
	// From The first day, written as YYYY-MM-DD.
	From *string `form:"from,omitempty" json:"from,omitempty"`

	// To The last day, written as YYYY-MM-DD.
	To *string `form:"to,omitempty" json:"to,omitempty"`
}

// GetAnnouncementParams defines parameters for GetAnnouncement.
type GetAnnouncementParams struct {
	// Channel The channel the preview would post to, whose members an owner not yet linked is checked against; the configured channel when left out.
	Channel *string `form:"channel,omitempty" json:"channel,omitempty"`
}

// PreviewBranchIssueParams defines parameters for PreviewBranchIssue.
type PreviewBranchIssueParams struct {
	// Key A Jira key, or a forge issue number with or without its
	Key string `form:"key" json:"key"`
}

// GetChangeDiffParams defines parameters for GetChangeDiff.
type GetChangeDiffParams struct {
	// Path The changed file's path, as the working tree's changes list it.
	Path string `form:"path" json:"path"`
}

// UpdateConfigParams defines parameters for UpdateConfig.
type UpdateConfigParams struct {
	// IfMatch The ETag of the read the change was made over. A write without it is refused with 428, one whose value is not in the form of an ETag a read returns with 400, and one naming a revision the file is no longer at with 409.
	IfMatch *string `json:"If-Match,omitempty"`
}

// GetDirectoriesParams defines parameters for GetDirectories.
type GetDirectoriesParams struct {
	// Path The directory to list.
	Path *string `form:"path,omitempty" json:"path,omitempty"`
}

// StreamEventsParams defines parameters for StreamEvents.
type StreamEventsParams struct {
	// View The configured view's name whose issues to include; the default view when omitted.
	View *string `form:"view,omitempty" json:"view,omitempty"`
}

// ListIssuesParams defines parameters for ListIssues.
type ListIssuesParams struct {
	// View The configured view's name; the default view when omitted.
	View *string `form:"view,omitempty" json:"view,omitempty"`

	// StartAt The zero-based index of the first issue to return.
	StartAt *int `form:"start_at,omitempty" json:"start_at,omitempty"`
}

// RemoveLocalDataParams defines parameters for RemoveLocalData.
type RemoveLocalDataParams struct {
	// Scope cache removes workflow.db; all also removes kept.db.
	Scope RemoveLocalDataParamsScope `form:"scope" json:"scope"`
}

// RemoveLocalDataParamsScope defines parameters for RemoveLocalData.
type RemoveLocalDataParamsScope string

// ForgetPersonParams defines parameters for ForgetPerson.
type ForgetPersonParams struct {
	// Owner The forge owner, a user or org/team.
	Owner OwnerName `form:"owner" json:"owner"`
}

// GetPullRequestDraftParams defines parameters for GetPullRequestDraft.
type GetPullRequestDraftParams struct {
	// Template The template to start the body from, by name; the repository's first when omitted.
	Template *string `form:"template,omitempty" json:"template,omitempty"`
}

// RemoveFavoriteParams defines parameters for RemoveFavorite.
type RemoveFavoriteParams struct {
	// Dir The directory, as an absolute path.
	Dir string `form:"dir" json:"dir"`
}

// GetSlackMembersParams defines parameters for GetSlackMembers.
type GetSlackMembersParams struct {
	// Channel The channel, by name or ID; the configured channel when left out.
	Channel *string `form:"channel,omitempty" json:"channel,omitempty"`
}

// PostActivityJSONRequestBody defines body for PostActivity for application/json ContentType.
type PostActivityJSONRequestBody = ActivityPostRequest

// AnnounceJSONRequestBody defines body for Announce for application/json ContentType.
type AnnounceJSONRequestBody = AnnounceRequest

// LinkBranchIssueJSONRequestBody defines body for LinkBranchIssue for application/json ContentType.
type LinkBranchIssueJSONRequestBody = BranchIssueRequest

// CreateBranchJSONRequestBody defines body for CreateBranch for application/json ContentType.
type CreateBranchJSONRequestBody = CreateBranchRequest

// CheckoutJSONRequestBody defines body for Checkout for application/json ContentType.
type CheckoutJSONRequestBody = CheckoutRequest

// CommitJSONRequestBody defines body for Commit for application/json ContentType.
type CommitJSONRequestBody = CommitRequest

// UpdateConfigJSONRequestBody defines body for UpdateConfig for application/json ContentType.
type UpdateConfigJSONRequestBody = Config

// SetUpJSONRequestBody defines body for SetUp for application/json ContentType.
type SetUpJSONRequestBody = SetupRequest

// DiscardJSONRequestBody defines body for Discard for application/json ContentType.
type DiscardJSONRequestBody = DiscardRequest

// SetUpHooksJSONRequestBody defines body for SetUpHooks for application/json ContentType.
type SetUpHooksJSONRequestBody = HookSetupRequest

// AssignIssueJSONRequestBody defines body for AssignIssue for application/json ContentType.
type AssignIssueJSONRequestBody = AssignRequest

// AddCommentJSONRequestBody defines body for AddComment for application/json ContentType.
type AddCommentJSONRequestBody = CommentRequest

// ChangeStatusJSONRequestBody defines body for ChangeStatus for application/json ContentType.
type ChangeStatusJSONRequestBody = StatusChangeRequest

// LogWorkJSONRequestBody defines body for LogWork for application/json ContentType.
type LogWorkJSONRequestBody = WorklogRequest

// LinkPersonJSONRequestBody defines body for LinkPerson for application/json ContentType.
type LinkPersonJSONRequestBody = PersonLink

// EditPullRequestJSONRequestBody defines body for EditPullRequest for application/json ContentType.
type EditPullRequestJSONRequestBody = PullRequestText

// OpenPullRequestJSONRequestBody defines body for OpenPullRequest for application/json ContentType.
type OpenPullRequestJSONRequestBody = OpenPullRequestRequest

// MergePullRequestJSONRequestBody defines body for MergePullRequest for application/json ContentType.
type MergePullRequestJSONRequestBody = MergeRequest

// SetRepoGroupsJSONRequestBody defines body for SetRepoGroups for application/json ContentType.
type SetRepoGroupsJSONRequestBody = RepoGroupsRequest

// AddFavoriteJSONRequestBody defines body for AddFavorite for application/json ContentType.
type AddFavoriteJSONRequestBody = DirectoryChoice

// SwitchRepositoryJSONRequestBody defines body for SwitchRepository for application/json ContentType.
type SwitchRepositoryJSONRequestBody = DirectoryChoice

// StartRunJSONRequestBody defines body for StartRun for application/json ContentType.
type StartRunJSONRequestBody = RunRequest

// StageJSONRequestBody defines body for Stage for application/json ContentType.
type StageJSONRequestBody = StagingRequest

// AddTaskJSONRequestBody defines body for AddTask for application/json ContentType.
type AddTaskJSONRequestBody = TaskLine

// TrackIssueJSONRequestBody defines body for TrackIssue for application/json ContentType.
type TrackIssueJSONRequestBody = TrackIssueRequest

// AnnotateTaskJSONRequestBody defines body for AnnotateTask for application/json ContentType.
type AnnotateTaskJSONRequestBody = TaskText

// ModifyTaskJSONRequestBody defines body for ModifyTask for application/json ContentType.
type ModifyTaskJSONRequestBody = TaskLine

// UnstageJSONRequestBody defines body for Unstage for application/json ContentType.
type UnstageJSONRequestBody = StagingRequest

// CreateWorktreeJSONRequestBody defines body for CreateWorktree for application/json ContentType.
type CreateWorktreeJSONRequestBody = CreateWorktreeRequest
