// Copyright 2026 Jacob Delgado
// SPDX-License-Identifier: Apache-2.0

// Command docsgen writes the command reference for the documentation site from
// the Cobra command tree, so the published flags are the flags the binary
// actually has.
//
// Run it through the Taskfile rather than directly:
//
//	task docs:gen
//
// scripts/check-docs-drift.sh fails the build when the committed pages and the
// command tree disagree, which is what stops a new flag from shipping
// undocumented.
package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra/doc"

	"github.com/jacob-delgado/workflow/internal/cli"
)

// exitFailure is the status returned when generation fails.
const exitFailure = 1

// dirMode is the permission for the output directory.
const dirMode os.FileMode = 0o755

// argCount is the number of arguments this tool takes, including its own name.
const argCount = 2

// weightStep spaces the Hugo sort weights of successive command depths.
const weightStep = 10

// errUsage reports a missing output directory argument.
var errUsage = errors.New("usage: docsgen <output-directory>")

// generatedNotice heads every file, because the one thing a reader must know
// about these pages is that editing them here achieves nothing.
const generatedNotice = "Generated by `task docs:gen` from the command tree. Do not edit."

func main() {
	err := run()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(exitFailure)
	}
}

// run writes the reference pages into the directory named by the first
// argument.
func run() error {
	if len(os.Args) < argCount {
		return errUsage
	}

	// The drift check generates into a temporary directory to compare against
	// the committed pages, so an absolute path outside the repository is a
	// legitimate destination. What keeps a mistyped argument from destroying
	// somebody's notes is removeGeneratedPages, which deletes only files this
	// tool wrote.
	outDir := filepath.Clean(os.Args[1])

	err := os.MkdirAll(outDir, dirMode)
	if err != nil {
		return fmt.Errorf("creating %s: %w", outDir, err)
	}

	// Remove pages from a previous run so a renamed or deleted command cannot
	// leave an orphan page behind, describing something that no longer exists.
	err = removeGeneratedPages(outDir)
	if err != nil {
		return err
	}

	root := cli.NewRootCmd()
	// Cobra stamps a "generated by spf13/cobra" footer with today's date, which
	// would make every run a diff and every diff meaningless.
	root.DisableAutoGenTag = true

	err = doc.GenMarkdownTreeCustom(root, outDir, frontMatter, hugoLink)
	if err != nil {
		return fmt.Errorf("generating command reference: %w", err)
	}

	return nil
}

// removeGeneratedPages deletes pages left by an earlier run, so a renamed or
// deleted command cannot leave an orphan page behind describing something that
// no longer exists.
//
// It removes ONLY files carrying this tool's generated notice. Hand-written
// pages in the same directory survive, and so does anything else the directory
// happens to contain — a mistyped destination costs a confusing error, not
// somebody's files.
func removeGeneratedPages(outDir string) error {
	entries, err := os.ReadDir(outDir)
	if err != nil {
		return fmt.Errorf("reading %s: %w", outDir, err)
	}

	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".md") {
			continue
		}

		path := filepath.Join(outDir, name)

		//nolint:gosec // a developer tool whose output directory is its argument
		contents, readErr := os.ReadFile(path)
		if readErr != nil {
			return fmt.Errorf("reading %s: %w", path, readErr)
		}

		if !strings.Contains(string(contents), generatedNotice) {
			continue
		}

		err = os.Remove(path)
		if err != nil {
			return fmt.Errorf("removing stale page %s: %w", name, err)
		}
	}

	return nil
}

// frontMatter returns the Hugo front matter for one generated page. The title
// is the command line itself ("workflow config init"), which is what a reader
// scanning the navigation is looking for.
func frontMatter(filename string) string {
	base := strings.TrimSuffix(filepath.Base(filename), ".md")
	title := strings.ReplaceAll(base, "_", " ")

	// Sort by depth, so `workflow` precedes `workflow config`, which precedes
	// `workflow config init`.
	weight := (strings.Count(base, "_") + 1) * weightStep

	return fmt.Sprintf(`---
title: "%s"
weight: %d
---

<!-- %s -->

`, title, weight, generatedNotice)
}

// hugoLink rewrites Cobra's "workflow_config.md" cross-references into the
// relative URLs Hugo serves.
func hugoLink(filename string) string {
	base := strings.TrimSuffix(filename, ".md")

	return "../" + strings.ToLower(base) + "/"
}
